/* Original paper-city artwork and a small shared platform/input loop. */
window.W = (() => {
  const c = document.querySelector('canvas'), ctx = c.getContext('2d'), $ = id => document.getElementById(id);
  const C = {ink:'#36463e',paper:'#f8f2df',green:'#537d63',mint:'#b8ceb5',orange:'#dc7852',yellow:'#e8bd62',blue:'#a9c8c5',pink:'#e5ab99',wall:'#e6e9d8'};
  const levels = {}, held = new Set(), zones = new Map();
  let s, last=0, activeDrag=null, audio, sound=true, unlocked=1, records={}, savedLevel=1, modal=false, hintStep=0, run=0, dialogPointer=false;
  const dev = new URLSearchParams(location.search).get('dev') === '1';
  try { const save=JSON.parse(localStorage.getItem('wulong-city-v1')||'{}'); unlocked=Math.max(1,Math.min(20,Number(save.unlocked)||1)); records=save.records&&typeof save.records==='object'?save.records:{}; savedLevel=Number(save.level)||1; sound=save.sound!==false; } catch {}
  function save(){try{localStorage.setItem('wulong-city-v1',JSON.stringify({unlocked,records,level:s.id,sound}));}catch{say('浏览器未允许存档，本次仍可继续游玩。');}}
  function tone(freq=420,duration=.1){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)(); if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.75,audio.currentTime+duration);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
  function say(message){if(s)s.feedback=message;$('feedback').textContent=message;}
  function rect(x,y,w,h,fill=C.paper,r=0,stroke=C.ink){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
  function line(x,y,a,b,col=C.ink,width=2,dash=[]){ctx.beginPath();ctx.setLineDash(dash);ctx.moveTo(x,y);ctx.lineTo(a,b);ctx.strokeStyle=col;ctx.lineWidth=width;ctx.stroke();ctx.setLineDash([]);}
  function ellipse(x,y,rx,ry,fill=C.paper,stroke=C.ink){ctx.beginPath();ctx.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
  function text(t,x,y,size=14,col=C.ink,align='center'){ctx.font=`${size>=24?'bold ':''}${size}px "Microsoft YaHei","PingFang SC",sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle=col;ctx.fillText(t,x,y);}
  function poly(points,fill,stroke=C.ink){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
  function face(x,y,look=1,mood='happy',scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);let blink=s&&Math.sin(s.t*1.7)> .997;for(const a of [-8,8]){ellipse(a,0,3.8,blink?1:5,C.paper,null);ellipse(a+look*1.5,0,1.9,blink?.6:3,C.ink,null);}if(mood==='fear'){ellipse(0,13,5,7,C.paper);line(-13,-8,-5,-11);line(5,-11,13,-8);}else{ctx.beginPath();ctx.arc(0,6,7,.2,Math.PI-.2);ctx.strokeStyle=C.ink;ctx.lineWidth=2;ctx.stroke();}if(mood==='shy'){ellipse(-16,8,6,3,C.pink,null);ellipse(16,8,6,3,C.pink,null);}ctx.restore();}
  function actor(x,y,dir=1,scale=1,pose='normal'){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const step=s&&Math.abs(s.p.vx)>1?Math.sin(s.t*15)*3:0;ellipse(0,1,17,4,'#485d4920',null);line(-7,-11,-9+step,0,C.ink,4);line(7,-11,9-step,0,C.ink,4);rect(-14,-33,28,24,C.green,7);line(-17,-27,-20,-13,C.ink,3);line(17,-27,20,-15,C.ink,3);rect(-15,-58,30,29,C.paper,12);ellipse(dir*5-5,-46,2,2,C.ink,null);ellipse(dir*5+5,-46,2,2,C.ink,null);line(dir*3,-38,dir*3+5,-38);poly([[-20,-56],[-15,-68],[11,-68],[16,-55],[24,-55],[24,-51],[-20,-51]],C.yellow);line(-5,-69,1,-75,C.ink,2);line(1,-75,7,-69,C.ink,2);poly([[-11,-31],[0,-28],[12,-32],[8,-24],[-1,-26],[-11,-20]],C.orange);rect(9,-21,14,11,C.yellow,2);if(pose==='grab'){line(-20,-52,-28,-60,C.orange);line(20,-52,28,-60,C.orange);}ctx.restore();}
  function bird(x,y,dir=1,color=C.green){ctx.save();ctx.translate(x,y);ctx.scale(dir,1);line(-12,8,15,8,C.ink,3);poly([[-8,0],[-16,16],[0,8]],color);ellipse(0,-10,13,20,color);ellipse(4,-22,12,12,color);poly([[14,-26],[23,-20],[13,-17]],C.yellow);ellipse(8,-25,3,3,C.paper);ellipse(9,-25,1.4,1.4,C.ink);line(-5,7,-5,11);line(5,7,5,11);ctx.restore();}
  function sign(label,x,y,w=90){line(x,y+20,x,y+60,'#9ca58f',3);rect(x-w/2,y-13,w,29,C.paper,3);text(label,x,y+2,12);}
  function handle(x,y,label=''){ellipse(x,y,10,10,C.yellow);ellipse(x,y,4,4,C.paper);if(label)text(label,x,y+25,11,C.green);}
  function door(x,y,open=false,label='出口'){rect(x-24,y-87,48,87,open?'#6c8468':C.mint,18);if(open){rect(x-15,y-69,30,69,'#3e5746',5,null);}else ellipse(x+14,y-41,3,3,C.yellow);text(label,x,y-103,12,C.green);}
  function background(kind='street'){rect(0,0,480,520,'#eef0e2',0,null);if(kind==='inside'){rect(22,28,436,408,'#f2eddc',12,'#d3d8c5');for(let x=42;x<470;x+=36)line(x,34,x,431,'#e4e0cd',1);line(22,317,458,317,'#d4d8c4',4);}else{ellipse(395,65,25,25,'#ecd69b',null);for(let i=0;i<7;i++){let x=i*77-13,top=172+(i%3)*23;rect(x,top,67,266-top,i%2?'#dce2d2':'#d5dfd0',3,null);for(let j=0;j<2;j++)rect(x+15+j*27,top+16,10,17,'#f2efdd',2,null);}for(const x of [56,224]){ellipse(x,83,25,9,C.paper,null);ellipse(x+21,80,16,12,C.paper,null);}}rect(0,437,480,83,'#e3e4d1',0,null);line(0,436,480,436,'#7c9276',3);for(let x=8;x<480;x+=31)line(x,448,x+9,447,'#c3cbb6',1);for(let i=0;i<90;i++){let x=(i*139+37)%480,y=(i*83+12)%490;ellipse(x,y,.6,.6,'#7d826518',null);}}
  function hit(id,label,x,y,w,h,click,drag,up){const min=(drag?44:36)*480/(c.clientWidth||480),nw=Math.max(w,min),nh=Math.max(h,min);x=Math.max(0,Math.min(480-nw,x-(nw-w)/2));y=Math.max(0,Math.min(490-nh,y-(nh-h)/2));W.frameZones.set(id,{id,label,x,y,w:nw,h:nh,click,drag,up});}
  function near(x,range=65){return Math.abs(s.p.x-x)<range;}
  function win(){if(s.won)return;s.won=true;s.finishAt=s.t+1.1;s.p.vx=0;clearInput();tone(730,.22);say(LEVEL_DATA[s.id].joke);records[s.id]=LEVEL_DATA[s.id].record;unlocked=Math.max(unlocked,Math.min(20,s.id+1));save();}
  function clearInput(){held.clear();if(activeDrag){levels[s.id].cancel?.(s);activeDrag=null;}document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
  function close(){if($('dialog').open)$('dialog').close();modal=false;clearInput();last=0;$('canvas').focus({preventScroll:true});}
  function open(html){clearInput();dialogPointer=false;modal=true;$('dialog-body').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();$('dialog-body').querySelector('[data-close]')?.addEventListener('click',close);}
  // A held movement touch must not click a result button that appears beneath it.
  $('dialog').addEventListener('pointerdown',()=>{dialogPointer=true;});
  $('dialog').addEventListener('pointercancel',()=>{dialogPointer=false;});
  $('dialog').addEventListener('click',e=>{if(e.detail>0&&!dialogPointer){e.preventDefault();e.stopImmediatePropagation();}dialogPointer=false;},true);
  function heading(title,sub='乌龙城 · 临时维修部'){return `<button class="close" data-close aria-label="返回游戏">×</button><div class="eyebrow">${sub}</div><h2 id="dialog-title">${title}</h2>`;}
  function menu(){let html=heading('今天也要准时收工')+'<p>一件一件来，总会有办法。</p>';['先出得了门','街上的东西各有想法','邻居的问题不止一点点','办完这单就回家'].forEach((name,j)=>{html+=`<div class="eyebrow">0${j+1} / ${name}</div><div class="level-grid">`;for(let id=j*5+1;id<=j*5+5;id++){let enabled=levels[id]&&(dev||id<=unlocked);html+=`<button data-level="${id}" title="${LEVEL_DATA[id]?.title||'制作中'}" aria-label="第${id}关 ${LEVEL_DATA[id]?.title||'制作中'}${records[id]?' 已完成':''}" class="${records[id]?'done':''} ${s.id===id?'current':''}" ${enabled?'':'disabled'}>${String(id).padStart(2,'0')}</button>`;}html+='</div>';});html+='<div class="records">维修记录';for(let id=1;id<=20;id++)if(records[id]&&LEVEL_DATA[id])html+=`<div class="record">${String(id).padStart(2,'0')} / ${LEVEL_DATA[id].record}</div>`;html+='</div>';if(dev)html+='<p>开发选关：所有已实现关卡开放。</p>';open(html);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(Number(b.dataset.level)));}
  function result(){let d=LEVEL_DATA[s.id],end=s.id===20;open(heading(end?'本市今日故障全部处理完毕':'又修好了一点点',`工单 ${String(s.id).padStart(2,'0')} · 已归档`)+`<div class="stamp">处理完毕</div><p>“${d.joke}”</p><div class="ending">${end?'新增问题，明天再说。<br>公交司机、值班员和鹦鹉，现在都住隔壁。':d.record}</div><button class="primary" id="next">${end?'翻看今天的维修记录':'下一张工单 →'}</button><button class="secondary" id="again">再玩这关</button>`);$('next').onclick=()=>end?menu():start(levels[s.id+1]?s.id+1:2);$('again').onclick=()=>start(s.id);}
  function start(id){close();hintStep=0;run++;s={id,run,t:0,p:{x:65,y:436,vx:0,vy:0,dir:1,grounded:true},won:false,feedback:'',...levels[id].init()};W.s=s;$('title').textContent=LEVEL_DATA[id].title;$('goal').textContent=LEVEL_DATA[id].goal;$('chapter').textContent=`第${['一','二','三','四'][Math.floor((id-1)/5)]}章 · ${['先出得了门','街上的东西各有想法','邻居的问题不止一点点','办完这单就回家'][Math.floor((id-1)/5)]}`;$('counter').textContent=String(id).padStart(2,'0')+' / 20';say(LEVEL_DATA[id].intro);zones.clear();$('hotspots').replaceChildren();save();draw();}
  function jump(){if(modal||s.won)return;if(levels[s.id].jump?.(s)===false)return;if(s.p.grounded&&!s.locked){s.p.vy=-410;s.p.grounded=false;tone(340,.08);}}
  function physics(dt){const p=s.p;let axis=Number(held.has('right'))-Number(held.has('left'));p.vx=s.locked||s.won?0:axis*145;if(axis&&!s.locked&&!s.won)p.dir=axis;if(s.manual)return;const solids=[...(levels[s.id].floor===false?[]:[{x:-50,y:436,w:580,h:100}]),...(levels[s.id].platforms?.(s)||[])];p.x+=p.vx*dt;for(const q of solids)if(q.solid&&p.y>q.y+7&&p.y-52<q.y+q.h&&p.x+12>q.x&&p.x-12<q.x+q.w){if(p.vx>0)p.x=q.x-12;else if(p.vx<0)p.x=q.x+q.w+12;}p.x=Math.max(22,Math.min(458,p.x));const old=p.y;p.vy+=1050*dt;p.y+=p.vy*dt;p.grounded=false;for(const q of solids){if(p.vy>=0&&old<=q.y+4&&p.y>=q.y&&p.x+10>q.x&&p.x-10<q.x+q.w){p.y=q.y;p.vy=0;p.grounded=true;}}}
  function draw(){W.frameZones=new Map();ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,480,520);levels[s.id].draw(s);if(!s.hideActor)actor(s.p.x,s.p.y,s.p.dir,1,s.id===3?'grab':'normal');for(const [id,z] of W.frameZones){let b=zones.get(id)?.el;if(!b){b=document.createElement('button');b.className='hotspot';b.dataset.zone=id;$('hotspots').append(b);b.addEventListener('keydown',e=>{const zone=zones.get(id);if(!zone||modal)return;if((e.key==='Enter'||e.key===' ')&&zone.drag){e.preventDefault();e.stopPropagation();if(activeDrag?.id==='keyboard'&&activeDrag.z.id===id){const grab=activeDrag;activeDrag=null;grab.z.up?.();}else{clearInput();activeDrag={z:zone,p:{x:zone.x+zone.w/2,y:zone.y+zone.h/2},run,id:'keyboard',moved:false};say('抓住了'+zone.label+'。方向键调整，回车松开，Esc暂停并取消。');}return;}if((e.key==='Enter'||e.key===' ')&&zone.click){e.preventDefault();zone.click();tone();}if(zone.drag&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.stopPropagation();if(!activeDrag||activeDrag.id!=='keyboard'){clearInput();activeDrag={z:zone,p:{x:zone.x+zone.w/2,y:zone.y+zone.h/2},run,id:'keyboard',moved:false};}const p=activeDrag.p;p.x+=e.key==='ArrowLeft'?-35:e.key==='ArrowRight'?35:0;p.y+=e.key==='ArrowUp'?-40:e.key==='ArrowDown'?40:0;activeDrag.moved=true;zone.drag(p.x,p.y);}});}b.setAttribute('aria-label',z.label+(z.drag?'，可拖动；键盘回车抓起，方向键调整，回车松开':''));Object.assign(b.style,{left:z.x/480*100+'%',top:z.y/520*100+'%',width:z.w/480*100+'%',height:z.h/520*100+'%'});zones.set(id,{...z,el:b});}for(const [id,z] of zones)if(!W.frameZones.has(id)){z.el.remove();zones.delete(id);}}
  function frame(now){let dt=Math.min((now-last)/1000||0,1/30);last=now;if(s&&!modal){s.t+=dt;if(!s.won){physics(dt);levels[s.id].update?.(s,dt);}else if(!s.presented&&s.t>s.finishAt){s.presented=true;result();}draw();}requestAnimationFrame(frame);}
  function point(e){const b=c.getBoundingClientRect();return{x:(e.clientX-b.left)*480/b.width,y:(e.clientY-b.top)*520/b.height};}
  function boot(){let requested=Number(new URLSearchParams(location.search).get('level'));start(dev&&levels[requested]?requested:levels[savedLevel]&&savedLevel<=unlocked?savedLevel:levels[1]?1:2);$('sound').textContent=sound?'♪':'♩';$('sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');requestAnimationFrame(frame);}
  $('stage').addEventListener('pointerdown',e=>{if(modal||s.won)return;const p=point(e);let list=[...zones.values()].reverse();let z=list.find(z=>p.x>=z.x&&p.x<=z.x+z.w&&p.y>=z.y&&p.y<=z.y+z.h);if(z){e.preventDefault();activeDrag={z,p,run,id:e.pointerId,moved:false};$('stage').setPointerCapture(e.pointerId);tone(380,.05);}});
  $('stage').addEventListener('pointermove',e=>{if(!activeDrag||activeDrag.id!==e.pointerId||activeDrag.run!==run||modal)return;const p=point(e);if(Math.hypot(p.x-activeDrag.p.x,p.y-activeDrag.p.y)>4)activeDrag.moved=true;if(activeDrag.z.drag&&activeDrag.moved)activeDrag.z.drag(p.x,p.y);});
  $('stage').addEventListener('pointerup',e=>{if(!activeDrag||activeDrag.id!==e.pointerId)return;const {z,moved,run:started}=activeDrag;activeDrag=null;if(started!==run||modal)return;if(!moved)z.click?.();z.up?.();});
  $('stage').addEventListener('pointercancel',()=>{if(activeDrag)levels[s.id].cancel?.(s);activeDrag=null;});
  for(const action of ['left','right','jump']){const b=$(action);b.addEventListener('pointerdown',e=>{e.preventDefault();if(modal)return;b.setPointerCapture(e.pointerId);if(action==='jump')jump();else held.add(action);b.classList.add('pressed');});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{held.delete(action);b.classList.remove('pressed');});b.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();if(action==='jump')jump();else held.add(action);}});b.addEventListener('keyup',()=>held.delete(action));}
  document.addEventListener('keydown',e=>{if(modal)return;if(e.key==='Escape'){e.preventDefault();pause();return;}if(e.target.closest('button')&&e.target.dataset.zone)return;if(['ArrowLeft','a','A'].includes(e.key)){e.preventDefault();held.add('left');}if(['ArrowRight','d','D'].includes(e.key)){e.preventDefault();held.add('right');}if(e.code==='Space'&&!e.target.closest('button')){e.preventDefault();if(!e.repeat)jump();}});document.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))held.delete('left');if(['ArrowRight','d','D'].includes(e.key))held.delete('right');});
  function pause(){open(heading('歇一小会儿')+'<p>城市可以等你。所有动作已经暂停。</p><button class="primary" data-resume>继续维修</button><button class="secondary" data-menu>选关 / 退出本关</button>');document.querySelector('[data-resume]').onclick=close;document.querySelector('[data-menu]').onclick=menu;}
  window.addEventListener('blur',()=>{clearInput();if(s&&!modal&&!s.won)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(s&&!modal&&!s.won)pause();}});$('dialog').addEventListener('cancel',()=>{modal=false;clearInput();last=0;});$('dialog').addEventListener('close',()=>{if(!$('dialog').open){modal=false;last=0;$('canvas').focus({preventScroll:true});}});$('pause').onclick=pause;$('menu').onclick=menu;$('retry').onclick=()=>start(s.id);$('hint').onclick=()=>{const d=LEVEL_DATA[s.id];open(heading('换个角度看看')+`<div class="hint-step">提示 ${hintStep+1} / 3</div><p>${d.hints[hintStep]}</p><button class="primary" data-close-hint>回去试试</button><button class="secondary" data-more>${hintStep<2?'再明确一点':'重新看第一条'}</button>`);document.querySelector('[data-close-hint]').onclick=close;document.querySelector('[data-more]').onclick=()=>{hintStep=(hintStep+1)%3;$('hint').click();};};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♪':'♩';$('sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');save();tone();};$('fullscreen').onclick=async()=>{clearInput();try{if(document.fullscreenElement)await document.exitFullscreen();else if($('game').requestFullscreen)await $('game').requestFullscreen();else say('当前浏览器不支持全屏；可添加到主屏幕后游玩。');}catch{say('此浏览器未允许全屏，仍可正常游玩。');}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'退出全屏':'进入全屏');if(!modal)$('canvas').focus({preventScroll:true});});
  if(dev)window.__wulong={snapshot:()=>JSON.parse(JSON.stringify({state:s,modal,unlocked,records,sound,zones:[...zones.values()].map(({id,x,y,w,h,label})=>({id,x,y,w,h,label}))}))};
  return {C,ctx,rect,line,ellipse,text,poly,face,actor,bird,sign,handle,door,background,hit,near,win,say,tone,boot,levels,add:(id,l)=>levels[id]=l,clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),frameZones:new Map()};
})();
