/** Chapters are data: append another entry without changing the turn engine. */
export const CONTRACTS = [
  {
    id: 'fine-nib',
    name: '利锋契约',
    price: 12,
    description: '墨弹伤害 4 → 6。把有限的墨，用在锋刃上。',
    effect: 'attack',
    value: 2,
  },
  {
    id: 'wayfinder',
    name: '引路契约',
    price: 10,
    description: '绘路消耗 6 → 4。多走一条路，也能留住余墨。',
    effect: 'explore',
    value: 2,
  },
  {
    id: 'binding',
    name: '护页契约',
    price: 12,
    description: '生命上限 +1，立即恢复 1；此后治疗恢复 3。',
    effect: 'heal',
    value: 1,
  },
];

const prepare = { name: '蓄墨', damage: 0, tell: '身体缓缓鼓起。本回合不会攻击，适合出手。' };
const strike = {
  name: '扑击',
  damage: 2,
  tell: '墨滴绷成尖刺。本回合造成 2 点伤害，防守可完全挡下。',
};
const recover = { name: '散墨', damage: 0, tell: '墨迹散开。本回合不会攻击。' };
const slash = {
  name: '横扫',
  damage: 2,
  tell: '笔锋横向展开。本回合造成 2 点伤害，防守可完全挡下。',
};
const jab = {
  name: '刺页',
  damage: 1,
  tell: '一根墨针浮起。本回合造成 1 点伤害，防守可完全挡下。',
};
const foe = (name, hp, intents, description) => ({ name, hp, maxHp: hp, intents, description });

const rooms = [
  {
    id: 'arrival',
    name: '落笔处',
    kind: 'start',
    x: 8,
    y: 77,
    description: '你醒在一页未干的纸上。最后一滴墨，既是武器，也是归途。',
    hint: '沿纸上的虚线，画出第一条路。',
    rewardText: '起始：72 墨 · 5 生命',
  },
  {
    id: 'crossing',
    name: '断句长廊',
    kind: 'path',
    x: 23,
    y: 58,
    description: '三条笔迹通往不同的命运。北侧藏墨，东侧有钥印，南侧可以签约。',
    hint: '安全的岔路，连接藏书室、守卫与商人。',
    rewardText: '路线枢纽 · 无敌人',
  },
  {
    id: 'archive',
    name: '遗墨书库',
    kind: 'cache',
    x: 18,
    y: 26,
    description: '一瓶未曾启封的旧墨夹在书页里。路没有白走，纸记得每一次冒险。',
    hint: '可安全获得 20 墨，并通往疗愈泉。',
    rewardText: '+20 墨',
    reward: { ink: 20 },
  },
  {
    id: 'spring',
    name: '洗笔泉',
    kind: 'spring',
    x: 39,
    y: 20,
    description: '清水洗去伤口，却洗不掉你作出的选择。泉水只能使用一次。',
    hint: '一次性免费恢复 3 生命。',
    rewardText: '+3 生命 · 一次',
    reward: { hp: 3 },
  },
  {
    id: 'sentinel',
    name: '折页守卫',
    kind: 'combat',
    x: 42,
    y: 45,
    description: '第一枚钥印，被一个守着旧句子的墨灵吞下。看清它的动作，再决定落笔。',
    hint: '守卫 7 生命；胜利后领取第一枚钥印与 8 墨。',
    rewardText: '钥印 Ⅰ · +8 墨',
    enemy: foe('折页墨灵', 7, [prepare, strike, recover], '守着第一枚钥印的墨灵。'),
    reward: { seals: 1, ink: 8 },
  },
  {
    id: 'market',
    name: '无名契约师',
    kind: 'merchant',
    x: 44,
    y: 78,
    description: '“我不收金币。”兜帽下传来纸张摩擦的声音，“只收你尚未写出的可能。”',
    hint: '用墨签订永久契约：攻击、绘路或治疗。',
    rewardText: '三份契约 · 各限一次',
  },
  {
    id: 'reliquary',
    name: '封墨匣',
    kind: 'cache',
    x: 62,
    y: 88,
    description: '旧匣里积着浓墨。一只小墨怪蜷在锁上，你可以花墨速战，也可以观察后干笔取胜。',
    hint: '墨怪 4 生命；击败后获得 24 墨。',
    rewardText: '+24 墨',
    enemy: foe('匣中墨滴', 4, [prepare, jab, recover], '护着墨匣的小墨怪。'),
    reward: { ink: 24 },
  },
  {
    id: 'causeway',
    name: '留白石桥',
    kind: 'path',
    x: 62,
    y: 59,
    description: '桥下是没有尽头的空白。这里通往第二名守卫，亦通往终门。',
    hint: '安全枢纽。可以回访任何已经清理的房间。',
    rewardText: '安全通路 · 无敌人',
  },
  {
    id: 'garden',
    name: '洇墨庭院',
    kind: 'cache',
    x: 61,
    y: 24,
    description: '纸花吸满了雨夜的墨。你把它们拢在掌心，得到继续前行的分量。',
    hint: '可安全获得 16 墨，是前往第二枚钥印的另一条路。',
    rewardText: '+16 墨',
    reward: { ink: 16 },
  },
  {
    id: 'warden',
    name: '断笔骑士',
    kind: 'combat',
    elite: true,
    x: 79,
    y: 41,
    description: '第二枚钥印挂在断笔上。骑士每次蓄势后的横扫都很凶猛，散墨时却毫无防备。',
    hint: '骑士 10 生命；胜利后领取第二枚钥印与 10 墨。',
    rewardText: '钥印 Ⅱ · +10 墨',
    enemy: foe('断笔骑士', 10, [prepare, slash, recover, jab], '读懂横扫与刺页，才是最好的护甲。'),
    reward: { seals: 1, ink: 10 },
  },
  {
    id: 'lookout',
    name: '余白观台',
    kind: 'cache',
    x: 79,
    y: 76,
    description: '从这里能看见终门背后的红光。台上剩下一小瓶墨，以及上个旅人的一页绷带。',
    hint: '可安全获得 12 墨与 1 生命。',
    rewardText: '+12 墨 · +1 生命',
    reward: { ink: 12, hp: 1 },
  },
  {
    id: 'threshold',
    name: '终页门廊',
    kind: 'path',
    x: 89,
    y: 58,
    description: '两枚钥印，补全门上被擦去的标点。开门不需要墨，只需要你已经走过的路。',
    hint: '领取两枚钥印后可免费开启墨之门；可以先返回补给。',
    rewardText: '需要 2 枚钥印 · 开门免费',
  },
  {
    id: 'gate',
    name: '墨之门',
    kind: 'boss',
    elite: true,
    x: 93,
    y: 14,
    description: '所有被遗忘的墨汇成最后的守门者。不要把所有选择都留到下一页。',
    hint: '最终守门者 16 生命。先蓄墨、再横扫、散墨后刺页。',
    rewardText: '最终试炼 · 击败守门者通关',
    enemy: foe(
      '终页守门者',
      16,
      [prepare, slash, recover, jab],
      '终页的墨不会自己干去，必须由你结束这段旅程。',
    ),
  },
];

const links = [
  ['arrival', 'crossing'],
  ['crossing', 'archive'],
  ['archive', 'spring'],
  ['spring', 'sentinel'],
  ['crossing', 'sentinel'],
  ['crossing', 'market'],
  ['market', 'reliquary'],
  ['market', 'causeway'],
  ['sentinel', 'causeway'],
  ['sentinel', 'garden'],
  ['garden', 'warden'],
  ['causeway', 'warden'],
  ['causeway', 'lookout'],
  ['lookout', 'threshold'],
  ['warden', 'threshold'],
  ['threshold', 'gate'],
];

export const LEVELS = {
  'chapter-1': {
    id: 'chapter-1',
    title: '第一章 · 遗忘之庭',
    subtitle: '一滴墨，决定一切',
    description: '寻回两枚钥印，穿过墨之门。每一滴墨，同时承担探索、战斗、治疗与交易。',
    start: 'arrival',
    gate: 'gate',
    requiredSeals: 2,
    initial: { ink: 72, maxInk: 100, hp: 5, maxHp: 5 },
    rules: {
      drawCost: 6,
      attackCost: 5,
      attackDamage: 4,
      healCost: 8,
      healAmount: 2,
      traceEnemyBonus: 2,
      traceTurns: 2,
      traceDamage: 1,
    },
    contracts: CONTRACTS,
    rooms: rooms.map((room) => ({
      ...room,
      exits: links.flatMap(([a, b]) => (a === room.id ? [b] : b === room.id ? [a] : [])),
    })),
    links,
  },
};

export const levels = LEVELS;
