import assert from 'node:assert/strict';
import * as THREE from './vendor/three.module.js';
import { movePosition, framingScore, isPhotoObstructed } from './travel-3d.mjs';

const start = { x: 0, z: 0 };
const moved = movePosition(start, 2, -2, []);
assert.ok(Math.abs(moved.x - 2) < 1e-8 && Math.abs(moved.z + 2) < 1e-8);
assert.deepEqual(start, { x: 0, z: 0 });
const wall = [{ x: 0, z: -3, hx: 3, hz: 0.1 }];
assert.ok(movePosition(start, 0, -10, wall).z > -3, 'Movement must not tunnel through walls');
const slide = movePosition({ x: 0, z: -2.4 }, 2, -2, wall);
assert.ok(slide.x > 1.8 && slide.z > -3, 'Slide along an obstructing wall');
assert.ok(movePosition(start, 0, -8, [{ x: 0, z: -3, r: 0.8 }]).z > -3);
const bounded = movePosition(start, 100, -100, []);
assert.deepEqual(bounded, { x: 22, z: -24 });
assert.equal(framingScore(1, 15, true), 100);
assert.equal(framingScore(1, 15, false), 0);
assert.equal(framingScore(-1, 15, true), 0);
assert.ok(framingScore(0.99, 18, true) > framingScore(0.93, 18, true));
assert.equal(framingScore(NaN, 15, true), 0);
const blockingWall = new THREE.Mesh(new THREE.BoxGeometry(4, 4, 0.4), new THREE.MeshBasicMaterial());
blockingWall.position.set(0, 2, -3);
blockingWall.updateMatrixWorld();
assert.equal(isPhotoObstructed(new THREE.Vector3(0, 1.65, 0), new THREE.Vector3(0, 2, -10), [blockingWall]), true, 'A landmark behind a wall must not count as a photograph');
assert.equal(isPhotoObstructed(new THREE.Vector3(0, 1.65, 0), new THREE.Vector3(0, 15, -10), [blockingWall]), false, 'A tall landmark visible above a wall can be photographed');
blockingWall.position.z = -20;
blockingWall.updateMatrixWorld();
assert.equal(isPhotoObstructed(new THREE.Vector3(0, 1.65, 0), new THREE.Vector3(0, 2, -10), [blockingWall]), false, 'Objects beyond a landmark cannot obstruct it');
blockingWall.geometry.dispose();
blockingWall.material.dispose();
console.log('✓ 3D movement: collision, sliding, boundaries and real-camera framing passed.');
