/** Room data is deliberately separate from physics and presentation. Add a room here to extend the game. */
const floor = (x, y, w, h = 540 - y) => ({ x, y, w, h });
const robot = (id, x, y, toX, speed = 62) => ({
  id,
  kind: 'robot',
  x,
  y,
  w: 42,
  h: 46,
  speed,
  path: [
    { x, y },
    { x: toX, y },
  ],
});
const platform = (id, x, y, path, speed = 72, w = 142) => ({
  id,
  kind: 'platform',
  x,
  y,
  w,
  h: 18,
  speed,
  path: [{ x, y }, ...path],
});
const plate = (id, x, groundY, w = 68) => ({ id, x, y: groundY - 7, w, h: 7 });
const gate = (id, x, groundY, requires) => ({ id, x, y: groundY - 116, w: 24, h: 116, requires });
const exit = (x, groundY) => ({ x, y: groundY - 62, w: 48, h: 62 });

export const LEVELS = [
  {
    id: 'first-still',
    number: 1,
    kicker: '01 / 定格实验',
    title: '留住这一刻',
    goal: '让机器人停在开关上，再走进出口。',
    hint: [
      '拖动亮框：只有核心在框内的机器会运动。',
      '等机器人核心走到地面的压力开关上，再把框移开。',
      '机器人停住后会一直压住开关。你始终可以移动，跳过它并穿过打开的门。',
    ],
    spawn: { x: 78, y: 422 },
    frame: { x: 145, y: 230 },
    solids: [floor(0, 460, 960)],
    objects: [robot('keeper', 212, 414, 474, 68)],
    switches: [plate('a', 346, 460)],
    gates: [gate('door', 714, 460, ['a'])],
    exit: exit(868, 460),
  },
  {
    id: 'borrow-a-step',
    number: 2,
    kicker: '02 / 凝固的阶梯',
    title: '借一格高度',
    goal: '在合适的高度冻结升降台，把它变成阶梯。',
    hint: [
      '这个升降台也服从同一条规则。框外的它可以站立。',
      '让平台升到两侧地面之间，再移开观察框。',
      '把平台顶面停在两岸高度的中间。先从左岸跳到平台，站稳后再跳到右岸。',
    ],
    spawn: { x: 105, y: 422 },
    frame: { x: 260, y: 245 },
    solids: [floor(0, 460, 280), floor(492, 310, 468)],
    objects: [platform('lift', 315, 450, [{ x: 315, y: 265 }], 56)],
    switches: [],
    gates: [],
    exit: exit(866, 310),
  },
  {
    id: 'stay-with-it',
    number: 3,
    kicker: '03 / 同行视线',
    title: '别移开目光',
    goal: '登上横渡平台，让观察框陪它一起到对岸。',
    hint: [
      '先把平台留在左岸，再跳上去。',
      '平台中心离开亮框就会停车。站稳后，把框向右拖。',
      '不需要边走边跳：停在平台上，持续把核心保持在框内，到右岸再离开。',
    ],
    spawn: { x: 78, y: 392 },
    frame: { x: 0, y: 100 },
    solids: [floor(0, 430, 225), floor(738, 430, 222)],
    objects: [platform('ferry', 204, 420, [{ x: 740, y: 420 }], 86)],
    switches: [],
    gates: [],
    exit: exit(872, 430),
  },
  {
    id: 'one-frame-two-jobs',
    number: 4,
    kicker: '04 / 视线的取舍',
    title: '一个框，两件事',
    goal: '冻结开门的机器人，同时观察送你过河的平台。',
    hint: [
      '同一个亮框可以让一个物体动、另一个物体停。',
      '先把机器人留在开关上，再把亮框的左边界放到它的右边。',
      '机器人核心停在开关上后，框只需照着平台。跳上平台，向右拖框，门会一直保持打开。',
    ],
    spawn: { x: 64, y: 422 },
    frame: { x: 0, y: 250 },
    solids: [floor(0, 460, 310), floor(742, 370, 218)],
    objects: [
      robot('keeper', 112, 414, 277, 62),
      platform('ferry', 321, 433, [{ x: 670, y: 360 }], 76, 146),
    ],
    switches: [plate('a', 232, 460)],
    gates: [gate('door', 802, 370, ['a'])],
    exit: exit(885, 370),
  },
  {
    id: 'two-still-lives',
    number: 5,
    kicker: '05 / 分别暂停',
    title: '排练双重定格',
    goal: '让两个机器人同时压住各自的开关。',
    hint: [
      '门上的两盏灯分别连接两个开关。',
      '一次只排练一个机器人：先停好左侧，再向右移动亮框。',
      '把两枚机器人核心分别停在地面开关上。不要让已经停好的机器人重新进入观察框。',
    ],
    spawn: { x: 62, y: 422 },
    frame: { x: 80, y: 250 },
    solids: [floor(0, 460, 960)],
    objects: [robot('left-keeper', 170, 414, 336, 61), robot('right-keeper', 526, 414, 726, 69)],
    switches: [plate('a', 284, 460), plate('b', 671, 460)],
    gates: [gate('door', 813, 460, ['a', 'b'])],
    exit: exit(881, 460),
  },
  {
    id: 'final-rehearsal',
    number: 6,
    kicker: '06 / 最后的调度',
    title: '世界为你停一拍',
    goal: '调度两位守门人，乘平台抵达高处的出口。',
    hint: [
      '先处理左下方的开关，再搭乘沿折线前进的平台。',
      '第二个机器人在中间的舞台上。让它走到开关，再利用亮框边界把它排除。',
      '平台升到中间舞台附近、第二个机器人压住开关后，把框向上移：下边界越过机器人核心，却仍包住平台核心。然后跟随平台到出口。',
    ],
    spawn: { x: 56, y: 422 },
    frame: { x: 0, y: 250 },
    solids: [floor(0, 460, 309), floor(427, 400, 172), floor(772, 300, 188)],
    objects: [
      robot('lower-keeper', 132, 414, 266, 61),
      robot('upper-keeper', 438, 354, 551, 52),
      platform(
        'stair-ferry',
        281,
        435,
        [
          { x: 341, y: 355 },
          { x: 594, y: 315 },
          { x: 713, y: 287 },
        ],
        70,
        140,
      ),
    ],
    switches: [plate('a', 232, 460), plate('b', 508, 400)],
    gates: [gate('door', 840, 300, ['a', 'b'])],
    exit: exit(896, 300),
  },
];

export default LEVELS;
