/**
 * Original chapter 01: six boxes assembled from shafts, latches and panels.
 * Add levels as data: the engine and renderer do not branch on a level number.
 * Gate positions list the shaft detents that leave the shared ball channel open.
 */

const ROUTE = [
  [70, 120],
  [275, 190],
  [435, 245],
  [570, 290],
  [435, 335],
  [275, 380],
  [435, 430],
  [570, 475],
  [625, 515],
];
const COLORS = { A: '#e4ad59', B: '#64c5bb', C: '#e08b78' };
const RAILS = { A: 275, B: 435, C: 570 };
const shaft = (id, initial = 0, frontRole = '抬起正面挡门', backRole = '带动背面挡板') => ({
  id,
  label: `${id} 轴`,
  initial,
  min: 0,
  max: 2,
  x: RAILS[id],
  color: COLORS[id],
  notches: ['低', '中', '高'],
  frontRole,
  backRole,
});
const latch = (id, heldShaft, side, label, releaseWhen = [], y = 300) => ({
  id,
  shaft: heldShaft,
  side,
  initial: true,
  x: RAILS[heldShaft] + 58,
  y,
  label,
  releaseWhen,
});
const gate = (id, heldShaft, side, positions, pathIndex, label) => ({
  id,
  label,
  side,
  shaft: heldShaft,
  positions,
  x: ROUTE[pathIndex][0],
  y: ROUTE[pathIndex][1],
});
const checkpoint = (pathIndex, ...gateIds) => ({ pathIndex, gateIds });
const flip = () => ({ type: 'flip' });
const unlock = (id) => ({ type: 'latch', id });
const move = (id, value) => ({ type: 'shaft', id, value });
const release = () => ({ type: 'release' });
const advance = () => ({ type: 'advance' });
const route = () => ROUTE.map((point) => [...point]);

export const LEVELS = [
  {
    id: 'first-turn',
    number: 1,
    title: '打不开的正面',
    subtitle: '先找到固定轴的锁扣',
    intro: '让橙色小球进入终点槽。试着抬起 A 轴；如果拉不动，翻到背面看看。',
    shafts: [shaft('A', 0, '高位抬起挡门', '锁扣固定同一根轴')],
    latches: [latch('lock-A', 'A', 'back', 'A 轴锁扣')],
    gates: [gate('door-A', 'A', 'front', [2], 1, '起步挡门')],
    path: route(),
    checkpoints: [checkpoint(1, 'door-A'), checkpoint(8)],
    hints: [
      '正面挡门和背面锁扣都连着 A 轴。轴被锁住时，换挡不会生效。',
      '翻到背面，点开 A 轴右侧的大锁扣；再把 A 轴移到高位。',
      '回到正面放球。球道中没有其他挡板。',
    ],
    solution: [flip(), unlock('lock-A'), flip(), move('A', 2), release(), advance(), advance()],
    estimatedMoves: 5,
  },
  {
    id: 'middle-ground',
    number: 2,
    title: '刚刚好的中间',
    subtitle: '一个挡位，同时照顾两面',
    intro: 'A 轴越高，正面越通畅，背面的挡板却越低。观察两面的挡位标记。',
    shafts: [shaft('A', 0, '中 / 高位打开首门', '低 / 中位收起尾板')],
    latches: [latch('lock-A', 'A', 'back', 'A 轴锁扣')],
    gates: [
      gate('door-A', 'A', 'front', [1, 2], 1, '正面升降门'),
      gate('panel-A', 'A', 'back', [0, 1], 5, '背面反向挡板'),
    ],
    path: route(),
    checkpoints: [checkpoint(1, 'door-A'), checkpoint(5, 'panel-A'), checkpoint(8)],
    hints: [
      '同一根 A 轴抬起正面门，也会压下背面挡板。翻面不改变轴的位置。',
      '正面接受中位或高位；背面接受低位或中位。两面共同的挡位是中位。',
      '松开背面锁扣，把 A 轴移到中位，再回正面放球。',
    ],
    solution: [
      flip(),
      unlock('lock-A'),
      move('A', 1),
      flip(),
      release(),
      advance(),
      advance(),
      advance(),
    ],
    estimatedMoves: 5,
  },
  {
    id: 'aligned-window',
    number: 3,
    title: '对齐解锁窗',
    subtitle: '先让另一根轴为你让路',
    intro: 'A 轴的背面锁扣带有对齐窗。B 轴既是球道挡板，也是解开 A 轴的钥匙。',
    shafts: [
      shaft('A', 0, '高位打开起步门', 'B 中位才能松开锁扣'),
      shaft('B', 0, '中位让球通过', '中位对齐 A 解锁窗'),
    ],
    latches: [latch('lock-A', 'A', 'back', 'A 轴对齐锁扣', [{ shaft: 'B', positions: [1] }])],
    gates: [
      gate('door-A', 'A', 'front', [2], 1, '起步挡门'),
      gate('panel-B', 'B', 'front', [1], 2, '中位通道'),
    ],
    path: route(),
    checkpoints: [checkpoint(1, 'door-A'), checkpoint(2, 'panel-B'), checkpoint(8)],
    hints: [
      'A 的锁扣刻着「B · 中」。它会检查 B 轴当前的位置，不只是看锁扣所在的面。',
      '先把 B 轴移到中位，再到背面松开 A 轴锁扣。',
      'A 放到高位，B 留在中位，回正面放球。',
    ],
    solution: [
      move('B', 1),
      flip(),
      unlock('lock-A'),
      flip(),
      move('A', 2),
      release(),
      advance(),
      advance(),
      advance(),
    ],
    estimatedMoves: 6,
  },
  {
    id: 'moving-through',
    number: 4,
    title: '过门，再换挡',
    subtitle: '球停下来，机关仍然能动',
    intro: '前一道门需要 A 高位，后一道板需要 A 低位。没有一个挡位能一次打开整条球道。',
    shafts: [shaft('A', 0, '高位通过第一道门', '低位通过后段挡板')],
    latches: [latch('lock-A', 'A', 'back', 'A 轴锁扣')],
    gates: [
      gate('door-A', 'A', 'front', [2], 1, '先过高位门'),
      gate('panel-A', 'A', 'back', [0], 5, '再过低位板'),
    ],
    path: route(),
    checkpoints: [checkpoint(1, 'door-A'), checkpoint(5, 'panel-A'), checkpoint(8)],
    hints: [
      '高位和低位条件互相冲突。让球先通过第一道门，之后再改变 A 轴。',
      '松开背面锁扣，把 A 轴放到高位，再从正面放球。',
      '球停在后段挡板时，把 A 轴移到低位。已经通过的门不再阻挡这颗球。',
    ],
    solution: [
      flip(),
      unlock('lock-A'),
      flip(),
      move('A', 2),
      release(),
      advance(),
      move('A', 0),
      advance(),
      advance(),
    ],
    estimatedMoves: 6,
  },
  {
    id: 'crossed-latches',
    number: 5,
    title: '交错的两把锁',
    subtitle: '从高位起步，逐道改变条件',
    intro: 'B 的正面锁扣需要 A 高位，A 的背面锁扣需要 B 中位。先解开联锁，再护送小球。',
    shafts: [
      shaft('A', 2, '低位通过起步门', '中位通过末段挡板'),
      shaft('B', 0, '中位打开前段挡板', '高位打开后段挡板'),
    ],
    latches: [
      latch('lock-A', 'A', 'back', 'A 轴对齐锁扣', [{ shaft: 'B', positions: [1] }]),
      latch('lock-B', 'B', 'front', 'B 轴对齐锁扣', [{ shaft: 'A', positions: [2] }], 155),
    ],
    gates: [
      gate('door-A', 'A', 'front', [0], 1, 'A 低位起步门'),
      gate('door-B', 'B', 'front', [1], 2, 'B 中位前板'),
      gate('panel-B', 'B', 'back', [2], 4, 'B 高位后板'),
      gate('panel-A', 'A', 'back', [1], 5, 'A 中位尾板'),
    ],
    path: route(),
    checkpoints: [
      checkpoint(1, 'door-A'),
      checkpoint(2, 'door-B'),
      checkpoint(4, 'panel-B'),
      checkpoint(5, 'panel-A'),
      checkpoint(8),
    ],
    hints: [
      'A 一开始就在高位，满足正面 B 锁扣的解锁条件。先解开 B，再把 B 移到中位。',
      'B 中位会让背面 A 锁扣的窗口对齐。解开 A，把 A 放到低位后放球。',
      '球通过两道正面门后，让 B 升到高位；通过 B 后板后，让 A 移到中位。',
    ],
    solution: [
      unlock('lock-B'),
      move('B', 1),
      flip(),
      unlock('lock-A'),
      flip(),
      move('A', 0),
      release(),
      advance(),
      advance(),
      move('B', 2),
      advance(),
      move('A', 1),
      advance(),
      advance(),
    ],
    estimatedMoves: 9,
  },
  {
    id: 'three-shaft-relay',
    number: 6,
    title: '三轴接力',
    subtitle: '解开闭环，然后逐段送达',
    intro: 'A 低位释放 C，C 低位释放 B，B 中位释放 A。两面的六道挡板组成最后的接力球道。',
    shafts: [
      shaft('A', 0, '高位通过第一道门', '低位释放 C / 通过后板'),
      shaft('B', 2, '中位通过第二道门', '高位通过后段挡板'),
      shaft('C', 2, '低位通过第三道门', '高位通过终点挡板'),
    ],
    latches: [
      latch('lock-A', 'A', 'back', 'A 轴对齐锁扣', [{ shaft: 'B', positions: [1] }], 245),
      latch('lock-B', 'B', 'front', 'B 轴对齐锁扣', [{ shaft: 'C', positions: [0] }], 155),
      latch('lock-C', 'C', 'back', 'C 轴对齐锁扣', [{ shaft: 'A', positions: [0] }], 370),
    ],
    gates: [
      gate('door-A', 'A', 'front', [2], 1, 'A 高位首门'),
      gate('door-B', 'B', 'front', [1], 2, 'B 中位次门'),
      gate('door-C', 'C', 'front', [0], 3, 'C 低位第三门'),
      gate('panel-B', 'B', 'back', [2], 4, 'B 高位后板'),
      gate('panel-A', 'A', 'back', [0], 5, 'A 低位后板'),
      gate('panel-C', 'C', 'back', [2], 7, 'C 高位尾板'),
    ],
    path: route(),
    checkpoints: [
      checkpoint(1, 'door-A'),
      checkpoint(2, 'door-B'),
      checkpoint(3, 'door-C'),
      checkpoint(4, 'panel-B'),
      checkpoint(5, 'panel-A'),
      checkpoint(7, 'panel-C'),
      checkpoint(8),
    ],
    hints: [
      '从已经满足条件的锁扣开始：A 在低位，所以背面 C 锁扣现在就能松开。',
      '松开 C 后将它移到低位；回正面松开 B 并移到中位；再到背面松开 A。准备 A 高、B 中、C 低后放球。',
      '小球通过三道正面门后，依次把 B 移到高位、A 移到低位、C 移到高位。每次等球通过对应挡板再继续。',
    ],
    solution: [
      flip(),
      unlock('lock-C'),
      move('C', 0),
      flip(),
      unlock('lock-B'),
      move('B', 1),
      flip(),
      unlock('lock-A'),
      flip(),
      move('A', 2),
      release(),
      advance(),
      advance(),
      advance(),
      move('B', 2),
      advance(),
      move('A', 0),
      advance(),
      move('C', 2),
      advance(),
      advance(),
    ],
    estimatedMoves: 14,
  },
];

export default LEVELS;
