/** 每次只推进一个解锁窗口；解开最后一把锁后，再处理十二道板。 */
import { defineLevel } from './shared.mjs';

export default defineLevel({
  id: 'six-cycle',
  number: 49,
  title: '六角闭环',
  subtitle: '从前面的低位开始',
  intro: 'A 低位开 F，F 中位开 E，E 低位开 D，D 高位开 C，C 中位开 B，B 高位开 A。',
  lesson: '每次只推进一个解锁窗口；解开最后一把锁后，再处理十二道板。',
  difficulty: '大师',
  shafts: [
    ['A', 'front', 0],
    ['B', 'back', 0],
    ['C', 'left', 2],
    ['D', 'right', 0],
    ['E', 'top', 2],
    ['F', 'bottom', 0],
  ],
  latches: [
    ['lock-A', 'A', 'left', [['B', [2]]]],
    ['lock-B', 'B', 'top', [['C', [1]]]],
    ['lock-C', 'C', 'bottom', [['D', [2]]]],
    ['lock-D', 'D', 'front', [['E', [0]]]],
    ['lock-E', 'E', 'back', [['F', [1]]]],
    ['lock-F', 'F', 'right', [['A', [0]]]],
  ],
  preparation: [
    ['latch', 'lock-F'],
    ['shaft', 'F', 1],
    ['latch', 'lock-E'],
    ['shaft', 'E', 0],
    ['latch', 'lock-D'],
    ['shaft', 'D', 2],
    ['latch', 'lock-C'],
    ['shaft', 'C', 1],
    ['latch', 'lock-B'],
    ['shaft', 'B', 2],
    ['latch', 'lock-A'],
  ],
  route: [
    ['A', [2]],
    ['B', [1]],
    ['C', [0]],
    ['D', [1]],
    ['E', [1]],
    ['F', [2]],
    ['D', [0]],
    ['A', [0]],
    ['E', [2]],
    ['B', [0]],
    ['F', [0]],
    ['C', [2]],
  ],
});
