import {build} from 'esbuild';import {mkdir,readFile,writeFile}from'node:fs/promises';import{fileURLToPath}from'node:url';import{join}from'node:path';import{createHash}from'node:crypto';import assert from'node:assert/strict';
const out=fileURLToPath(new URL('../../../../../.scratch/travel-bund-native/contracts/',import.meta.url));await mkdir(out,{recursive:true});
await build({entryPoints:[fileURLToPath(new URL('../utf8.ts',import.meta.url)),fileURLToPath(new URL('../sha256.ts',import.meta.url)),fileURLToPath(new URL('../state.ts',import.meta.url)),fileURLToPath(new URL('../input.ts',import.meta.url))],outdir:out,bundle:true,format:'esm',platform:'neutral',mainFields:['module','main'],outExtension:{'.js':'.mjs'}});
const originalDecoder=globalThis.TextDecoder;delete globalThis.TextDecoder;
const {decodeUtf8,PortableUtf8Decoder}=await import(join(out,'utf8.mjs'));
const worldBytes=await readFile(new URL('../../../../../assets/bund/runtime/world/world.json',import.meta.url));assert.equal(decodeUtf8(worldBytes.buffer.slice(worldBytes.byteOffset,worldBytes.byteOffset+worldBytes.byteLength)),worldBytes.toString('utf8'));assert.equal(typeof globalThis.TextDecoder,'function');
for(const text of ['外滩漫游 · 江风','😀𠮷\u0000','\ufeff外滩']){const bytes=Buffer.from(text);assert.equal(decodeUtf8(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)),new originalDecoder().decode(bytes));}
const streaming=new PortableUtf8Decoder();assert.equal(streaming.decode(Uint8Array.of(0xe6),{stream:true}),'');assert.equal(streaming.decode(Uint8Array.of(0xb1,0x9f)),'江');assert.throws(()=>new PortableUtf8Decoder('utf8',{fatal:true}).decode(Uint8Array.of(0xc0)),TypeError);
for(const bytes of [Uint8Array.of(0xe0,0x80,0x80),Uint8Array.of(0xe1,0x80,0x41),Uint8Array.of(0xf4,0x90,0x80,0x80),Uint8Array.of(0xf0,0x90)])assert.equal(new PortableUtf8Decoder().decode(bytes),new originalDecoder().decode(bytes));globalThis.TextDecoder=originalDecoder;
const {sha256}=await import(join(out,'sha256.mjs'));
for(const length of [0,3,55,56,64,257,1048576]){const b=Buffer.alloc(length);for(let i=0;i<length;i++)b[i]=(i*31)%256;assert.equal(sha256(b.buffer.slice(b.byteOffset,b.byteOffset+b.length)),createHash('sha256').update(b).digest('hex'));}
const {createNativeState}=await import(join(out,'state.mjs')),data=JSON.parse(await readFile(new URL('../../../../../assets/bund/runtime/world/world.json',import.meta.url),'utf8'));
const storage={'travel-bund.visits.v1':'["customs-house"]','travel-bund.photo-hunts.v1':'{"version":1,"completed":["clock-tower"]}','travel-bund.render-detail.v1':'original','travel-bund.settings.v1':'{"night":true,"sound":false,"crowd":true,"motion":false}'};
const sdk={getStorageSync:k=>storage[k],setStorageSync:(k,v)=>storage[k]=v};const api=createNativeState(sdk,data);assert.deepEqual(api.state.visits,['customs-house']);assert.equal(api.state.night,true);assert.equal(api.state.renderDetail,'original');api.previewHunt('pearl-skyline');assert.equal(api.state.page,'home');api.chooseRoute('architecture');assert.equal(api.progress().completed,1);api.state.story=data.landmarks.find(l=>l.id==='hsbc-building');api.collect();api.collect();assert.equal(api.state.visits.filter(x=>x==='hsbc-building').length,1);assert.equal(api.progress().completed,2);api.toggle('sound');assert.equal(api.state.sound,false);assert.equal(api.state.audioAvailable,false);api.dispose();assert.ok(JSON.parse(storage['travel-bund.visits.v1']).includes('hsbc-building'));
const fixtureSdk={handlers:{}};for(const n of ['TouchStart','TouchMove','TouchEnd','TouchCancel']){fixtureSdk['on'+n]=fn=>fixtureSdk.handlers[n]=fn;fixtureSdk['off'+n]=()=>delete fixtureSdk.handlers[n];}
const {attachNativeInput}=await import(join(out,'input.mjs'));let clicks=0;const hud={hits:[{id:'button',x:10,y:10,w:50,h:50,run:()=>clicks++},{id:'joystick',x:10,y:100,w:128,h:128,run(){}}],point:p=>({id:p.identifier,x:p.clientX,y:p.clientY}),render(){},scroll(){}};const model={state:{active:true,zoom:1}};const inputs=attachNativeInput(fixtureSdk,hud,model),touch=(name,id,x,y)=>fixtureSdk.handlers[name]({changedTouches:[{identifier:id,clientX:x,clientY:y}]});touch('TouchStart',1,20,20);touch('TouchMove',1,100,100);touch('TouchEnd',1,20,20);assert.equal(clicks,0);touch('TouchStart',2,74,164);touch('TouchMove',2,115,164);touch('TouchStart',3,300,120);touch('TouchStart',4,350,120);touch('TouchMove',4,400,120);assert.ok(model.state.zoom>1);assert.deepEqual(inputs.snapshot().stick,[41/42,0]);touch('TouchCancel',4,400,120);touch('TouchCancel',2,115,164);assert.deepEqual(inputs.snapshot().stick,[0,0]);inputs.clear();assert.equal(inputs.snapshot().touches,0);inputs.dispose();assert.deepEqual(Object.keys(fixtureSdk.handlers),[]);
const report={checks:['without TextDecoder: exact authored world JSON/Chinese/emoji/BOM/stream/invalid UTF8','SHA256 exact seven boundaries including 1MiB','old visits/settings/model keys and valid normal progression','locked photo route rejects unauthorized entry','collect is idempotent','real missing audio declared unavailable','touch slide-out cancels click','joystick owns first contact while independent scene pinch zooms','cancel/clear/dispose release touch and listeners'],passed:true,scope:'pure UI/input/storage contracts, not scene/host/device acceptance'};await writeFile(new URL('../../docs/platforms/native-design-2026-10-06/contracts-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
