import { INK, TAU, random } from './palette.mjs';
import { drawLabel, inkBlot, stoneBlock } from './primitives.mjs';

export function createFloor(room) {
  const worldWidth = room.width || 960,
    worldHeight = room.height || 600;
  const boundary = room.boundary ?? 33;
  const surface = document.createElement('canvas');
  surface.width = worldWidth * 2;
  surface.height = worldHeight * 2;
  const ctx = surface.getContext('2d');
  ctx.scale(2, 2);
  const rng = random(`arena-${room.id || room.name}`);
  const gradient = ctx.createRadialGradient(
    worldWidth * 0.46,
    worldHeight * 0.4,
    80,
    worldWidth / 2,
    worldHeight / 2,
    Math.max(worldWidth, worldHeight) * 0.65,
  );
  gradient.addColorStop(0, '#ece0c4');
  gradient.addColorStop(0.6, '#ded0b0');
  gradient.addColorStop(1, '#b9aa8b');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, worldWidth, worldHeight);
  // Irregular flagstones: enough definition to make movement and range legible.
  for (let row = 0; row <= Math.ceil(worldHeight / 48); row++) {
    for (let col = -1; col <= Math.ceil(worldWidth / 57); col++) {
      const x = col * 57 + (row % 2) * 28,
        y = row * 48;
      ctx.strokeStyle = `rgba(69,69,51,${0.11 + rng() * 0.12})`;
      ctx.lineWidth = 0.7 + rng() * 0.6;
      ctx.fillStyle = rng() > 0.76 ? 'rgba(157,148,118,.1)' : 'rgba(255,244,214,.09)';
      ctx.beginPath();
      ctx.moveTo(x + 2, y + 2);
      ctx.lineTo(x + 52, y + rng() * 3);
      ctx.lineTo(x + 56 - rng() * 3, y + 43);
      ctx.lineTo(x + rng() * 3, y + 47);
      ctx.closePath();
      ctx.fill();
      ctx.stroke();
      if (rng() > 0.65) {
        ctx.beginPath();
        ctx.moveTo(x + 8, y + 7);
        ctx.lineTo(x + 18, y + 12);
        ctx.lineTo(x + 16, y + 20);
        ctx.moveTo(x + 18, y + 12);
        ctx.lineTo(x + 24, y + 13);
        ctx.stroke();
      }
    }
  }
  // Texture is deterministic and baked once, never generated by the frame loop.
  for (let i = 0; i < (worldWidth * worldHeight) / 128; i++) {
    const x = rng() * worldWidth,
      y = rng() * worldHeight;
    ctx.fillStyle = `rgba(63,52,35,${0.025 + rng() * 0.075})`;
    ctx.fillRect(x, y, 0.4 + rng() * 1.5, 0.4 + rng() * 1.5);
  }
  for (let i = 0; i < 64; i++) {
    const x = 55 + rng() * Math.max(1, worldWidth - 110),
      y = 56 + rng() * Math.max(1, worldHeight - 120);
    ctx.strokeStyle = 'rgba(50,51,35,.26)';
    ctx.lineWidth = 0.7;
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(x + 3, y - 2);
    ctx.lineTo(x + 7, y + 1);
    ctx.stroke();
  }
  // Dark, rough paper perimeter frames the playable page without obstructing it.
  ctx.fillStyle = '#30382a';
  ctx.fillRect(0, 0, worldWidth, boundary);
  ctx.fillRect(0, worldHeight - boundary, worldWidth, boundary);
  ctx.fillRect(0, 0, boundary, worldHeight);
  ctx.fillRect(worldWidth - boundary, 0, boundary, worldHeight);
  for (let i = 0; i <= Math.ceil(worldWidth / 45); i++) {
    stoneBlock(ctx, i * 45 - 9, -9 + rng() * 5, 45, boundary + 10, `north${i}`);
    stoneBlock(
      ctx,
      i * 45 - 9,
      worldHeight - boundary + 2 + rng() * 4,
      45,
      boundary + 8,
      `south${i}`,
    );
  }
  for (let i = 1; i <= Math.ceil(worldHeight / 45); i++) {
    stoneBlock(ctx, -18, i * 45, boundary + 18, 44, `west${i}`);
    stoneBlock(ctx, worldWidth - boundary + 4, i * 45, boundary + 20, 44, `east${i}`);
  }
  // Drawing-page ornamentation lives outside the action lanes.
  ctx.save();
  ctx.translate(85, 82);
  ctx.rotate(-0.12);
  ctx.globalAlpha = 0.19;
  ctx.strokeStyle = INK;
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.arc(0, 0, 26, 0, TAU);
  ctx.moveTo(-36, 0);
  ctx.lineTo(36, 0);
  ctx.moveTo(0, -36);
  ctx.lineTo(0, 36);
  ctx.stroke();
  ctx.restore();
  const obstacles = room.obstacles || [];
  for (const [index, ob] of obstacles.entries()) {
    const x = ob.x,
      y = ob.y,
      w = ob.w ?? ob.width ?? 60,
      h = ob.h ?? ob.height ?? 50;
    if (ob.kind === 'pit' || ob.type === 'pit' || ob.kind === 'void') {
      const depth = ctx.createLinearGradient(0, y, 0, y + h);
      depth.addColorStop(0, '#515541');
      depth.addColorStop(0.3, '#282e23');
      depth.addColorStop(0.8, '#22291f');
      depth.addColorStop(1, '#444c36');
      ctx.fillStyle = depth;
      ctx.fillRect(x, y, w, h);
      ctx.strokeStyle = '#9b9779';
      ctx.lineWidth = 1.5;
      for (let i = 0; i < w; i += 21) {
        ctx.beginPath();
        ctx.moveTo(x + i, y + 1);
        ctx.lineTo(x + i + 7, y + 5 + rng() * 4);
        ctx.lineTo(x + Math.min(w, i + 17), y + 2);
        ctx.moveTo(x + i, y + h - 1);
        ctx.lineTo(x + i + 9, y + h - 5 - rng() * 5);
        ctx.lineTo(x + Math.min(w, i + 19), y + h - 2);
        ctx.stroke();
      }
      for (let i = 0; i < (w * h) / 400; i++) {
        const px = x + rng() * w,
          py = y + 12 + rng() * (h - 24);
        ctx.fillStyle = 'rgba(10,15,8,.35)';
        ctx.beginPath();
        ctx.ellipse(px, py, 2 + rng() * 11, 1 + rng() * 3, -0.2, 0, TAU);
        ctx.fill();
      }
      if (w > 200)
        drawLabel(ctx, '未写出的深渊', x + w / 2, y + h / 2, {
          size: 14,
          color: '#8f957b',
          background: false,
        });
    } else if (ob.kind === 'ink' || ob.type === 'ink') {
      inkBlot(ctx, x + w / 2, y + h / 2, w / 2, index, 0.9);
    } else {
      const cols = Math.max(1, Math.round(w / 44)),
        rows = Math.max(1, Math.round(h / 33));
      for (let r = 0; r < rows; r++)
        for (let c = 0; c < cols; c++) {
          stoneBlock(
            ctx,
            x + (c * w) / cols,
            y + (r * h) / rows,
            w / cols + 0.5,
            h / rows,
            `${room.id}-${index}-${r}-${c}`,
          );
        }
      for (let i = 0; i < 3; i++) {
        const sx = x - 7 + rng() * (w + 14),
          sy = y + h + 8 + rng() * 7;
        ctx.fillStyle = '#948f73';
        ctx.strokeStyle = '#414633';
        ctx.beginPath();
        ctx.moveTo(sx, sy);
        ctx.lineTo(sx + 5, sy - 5);
        ctx.lineTo(sx + 10, sy - 1);
        ctx.lineTo(sx + 8, sy + 4);
        ctx.closePath();
        ctx.fill();
        ctx.stroke();
      }
    }
  }
  return surface;
}
