import assert from 'node:assert/strict';
import { createGame, startOrder, restart, tick, interact, target, contextAction, GOODS, MARKET, ORDERS } from '../src/game.js';

const at = (s, point) => Object.assign(s, { x: point.x, z: point.z, speed: 0 });
const s = createGame({ coins: Infinity, completed: -4 });
assert.equal(s.coins, 0);
assert.equal(s.completed, 0);
assert.equal(createGame(null).coins, 0);
assert.equal(createGame({ coins: 17.8, completed: 2 }).coins, 17);
tick(s, { throttle: 1 }, 0.1);
assert.equal(s.z, 16, 'menu must freeze motion');
startOrder(s, 0);
assert.equal(interact(s), false, 'pickup requires proximity');
at(s, { x: MARKET.x + 3, z: MARKET.z });
s.angle = 1;
s.speed = 5;
assert.equal(contextAction(s), '刹车停稳');
assert.equal(interact(s), false, 'pickup requires stopping');
s.speed = 0;
assert.equal(interact(s), true);
assert.equal(s.mode, 'walk');
assert.equal(interact(s), false, 'cannot mount without all goods');
for (const point of GOODS) {
  at(s, point);
  assert.equal(interact(s), true);
  assert.equal(interact(s), false, 'one pickup per item');
}
assert.equal(s.cargo, 3);
assert.deepEqual(target(s), { x: MARKET.x + 3, z: MARKET.z, name: '小摩托' });
at(s, { x: MARKET.x - 3, z: MARKET.z });
assert.equal(contextAction(s), null);
assert.equal(interact(s), false, 'mounting requires proximity to the parked scooter, not the market');
at(s, { x: s.bikeX, z: s.bikeZ + 2 });
s.angle = -2;
assert.equal(contextAction(s), '上车出发');
assert.equal(interact(s), true);
assert.equal(s.phase, 'deliver');
assert.deepEqual([s.x, s.z, s.angle], [s.bikeX, s.bikeZ, 1], 'mounting restores the parked scooter position and heading');
assert.equal(interact(s), false, 'delivery requires proximity');
at(s, ORDERS[0]);
assert.equal(interact(s), true);
assert.equal(s.result.delivered, true);
assert.equal(s.result.stars, 3);
assert.equal(s.coins, ORDERS[0].reward + s.result.tip);
assert.equal(s.completed, 1);
const earned = s.coins;
assert.equal(interact(s), false);
tick(s, { throttle: 1 }, 0.1);
assert.equal(s.coins, earned, 'settlement must not repeat');
assert.equal(s.speed, 0);
startOrder(s, 1);
assert.equal(target(s), MARKET);
assert.equal(s.orderIndex, 1);

const wall = { x: 0, z: 0, w: 10, d: 2 };
at(s, { x: 0, z: 3 });
s.phase = 'deliver';
s.angle = 0;
s.speed = 23;
tick(s, { throttle: 1, boost: true }, 0.1, [wall]);
assert(s.z >= 1.7 - 1e-9, 'substeps must prevent crossing the wall');
assert(s.integrity < 100);
assert(s.events.some(e => e.type === 'crash'));
at(s, { x: 0, z: 1.71 });
s.speed = 23;
s.integrity = 1;
s.crashCooldown = 0;
tick(s, { throttle: 1 }, 0.05, [wall]);
assert.equal(s.result.failed, true);
assert.equal(s.result.reward, 0);
assert.equal(s.coins, earned);
restart(s);
assert.equal(s.phase, 'pickup');
assert.equal(s.integrity, 100);
assert.equal(s.z, 16);
assert.equal(s.coins, earned);
const elapsed = s.elapsed;
for (const dt of [NaN, Infinity, -1, 0]) tick(s, { throttle: 1 }, dt);
assert.equal(s.elapsed, elapsed, 'invalid deltas must be ignored');
tick(s, { throttle: NaN, steer: Infinity }, 50);
assert(s.elapsed <= elapsed + 0.100001, 'long frames must be bounded');
assert(Number.isFinite(s.x) && Number.isFinite(s.angle));
s.elapsed = 179.98;
tick(s, {}, 0.05);
assert.equal(s.result.failed, true, 'timeout must end the order');
assert.equal(s.result.reason, '超时了，休息一下再出发吧');
assert.equal(s.coins, earned);
restart(s);
at(s, { x: 65, z: 0 });
s.angle = Math.PI / 2; s.speed = 15;
tick(s, { throttle: 1 }, 0.1);
assert(s.x > 66, 'the coast beyond the old square boundary must be reachable');
for (const [mode, radius] of [['ride', 0.7], ['walk', 0.42]]) {
  s.mode = mode;
  const limit = 73 - radius;
  for (let i = 1; i < 16; i++) {
    const angle = i / 16 * Math.PI * 2;
    at(s, { x: Math.sin(angle) * (limit - .05), z: Math.cos(angle) * (limit - .05) });
    s.angle = Math.PI - angle; s.speed = mode === 'ride' ? 23 : 4.8;
    tick(s, { throttle: 1, jump: true }, 0.1);
    assert(Math.hypot(s.x, s.z) <= limit + 1e-9, 'the circular coast must remain solid, including during jumps');
  }
  at(s, { x: 57, z: 57 });
  tick(s, {}, 0.05);
  assert(Math.hypot(s.x, s.z) <= limit + 1e-9, 'old square corners must project back onto land');
  assert(Math.abs(s.x - s.z) < 1e-9, 'shore projection must choose the nearest land point');
  at(s, { x: 0, z: 72 });
  s.angle = Math.PI;
  for (let i = 0; i < 100; i++) tick(s, { throttle: 1 }, 0.05);
  assert(s.z > 84 && s.z <= 85 - radius + 1e-9, 'the dock must be reachable through its land connection and have a solid end');
  at(s, { x: 3 - radius - .05, z: 80 });
  s.angle = Math.PI / 2; s.speed = mode === 'ride' ? 23 : 4.8;
  tick(s, { throttle: 1 }, 0.1);
  assert(s.x <= 3 - radius + 1e-9 && s.z === 80, 'dock sides must stop the player before entering the sea');
  at(s, { x: 5, z: 80 });
  tick(s, {}, 0.05);
  assert.equal(s.x, 3 - radius, 'points beside the dock must project onto the nearer dock');
}
restart(s);
tick(s, { jump: true }, 0.05);
assert(s.jumpY > 0);
for (let i = 0; i < 20; i++) tick(s, {}, 0.05);
assert.equal(s.jumpY, 0, 'jumps must land');
s.energy = 0.2;
tick(s, { throttle: 1, boost: true }, 0.1);
assert.equal(s.boosting, false, 'empty energy must stop boost');
assert(s.energy >= 0 && s.energy <= 100);
console.log('Game checks passed: delivery, proximity, collision, circular coast, dock, failure, restart, timing, jump, and boost.');
