/** Existing dev build catalogue, retained while adding campaign content.
 * Run upgrades use kill XP; permanent growth lives separately in progression.mjs.
 */
export const BOONS = {
  shrub: Object.freeze({
    id: 'shrub',
    kind: 'thorn',
    name: '花叶灌木',
    color: '#81da65',
    description: '每 3.6 秒在来敌前方生长灌木，减速 58%，每秒造成 12 点伤害。',
    interval: 3.6,
    life: 14,
    radius: 58,
    slow: 0.42,
    damagePerSecond: 12,
  }),
  trench: Object.freeze({
    id: 'trench',
    kind: 'trench',
    name: '缓行沟渠',
    color: '#c2a878',
    description: '每 4 秒形成一道浅沟，踏入沟渠的敌人减速 72%，角色可自由通过。',
    interval: 4,
    life: 15,
    radius: 86,
    slow: 0.28,
  }),
  frost: Object.freeze({
    id: 'frost',
    kind: 'frost',
    name: '霜冻花圃',
    color: '#a0e5fa',
    description: '每 4.8 秒铺出霜花，冻结敌人 0.9 秒；同一敌人 3 秒内不会再次冻结。',
    interval: 4.8,
    life: 12,
    radius: 66,
    freezeDuration: 0.9,
    freezeCooldown: 3,
  }),
  poison: Object.freeze({
    id: 'poison',
    kind: 'poison',
    name: '毒雾花丛',
    color: '#b1cd6c',
    description: '每 4.2 秒长出毒花，敌人中毒后每秒受到 10 点伤害，离开后持续 3 秒。',
    interval: 4.2,
    life: 13,
    radius: 66,
    poisonDuration: 3,
    damagePerSecond: 10,
  }),
  ice: Object.freeze({
    id: 'ice',
    kind: 'ice',
    name: '寒冰柱',
    color: '#67d4ff',
    description: '每 7 秒长出冰柱，阻挡双方移动与子弹；怪物会绕行或击碎它。',
    interval: 7,
    life: 12,
    radius: 28,
    health: 105,
    unlockPlayerLevel: 1,
    art: 'docs/design/concepts/growth-weapons-plants.png',
  }),
  mushroom: Object.freeze({
    id: 'mushroom',
    kind: 'mushroom',
    name: '爆炸蘑菇',
    color: '#ffb34b',
    description: '每 6 秒自动长出蘑菇，2.4 秒后爆炸，造成范围伤害。',
    interval: 6,
    life: 2.4,
    radius: 23,
    health: 1,
    unlockPlayerLevel: 1,
    art: 'docs/design/concepts/growth-weapons-plants.png',
  }),
  sunflower: Object.freeze({
    id: 'sunflower',
    kind: 'sunflower',
    name: '暖阳花',
    color: '#f5d467',
    description: '每 6 秒自动生长暖阳花，范围内每秒恢复 3 生命，多株最多回复 5。',
    interval: 6,
    life: 12,
    radius: 24,
    health: 45,
    unlockPlayerLevel: 2,
    art: 'docs/design/concepts/growth-weapons-plants.png',
  }),
  stormreed: Object.freeze({
    id: 'stormreed',
    kind: 'stormreed',
    name: '引雷芦',
    color: '#79dfef',
    description: '每 6.5 秒自动生长引雷芦，对空电击并连锁一个邻近目标。',
    interval: 6.5,
    life: 12,
    radius: 23,
    health: 55,
    unlockPlayerLevel: 4,
    art: 'docs/design/concepts/growth-weapons-plants.png',
  }),
  bloomturret: Object.freeze({
    id: 'bloomturret',
    kind: 'bloomturret',
    name: '花瓣炮',
    color: '#f193d4',
    description: '每 6 秒自动生长花瓣炮，每 0.9 秒射击最近目标。',
    interval: 6,
    life: 13,
    radius: 26,
    health: 65,
    unlockPlayerLevel: 6,
    art: 'docs/design/concepts/growth-weapons-plants.png',
  }),
};

/** Energy fills through combat time and kills; every skill requires a manual cast. */
export const SKILLS = Object.freeze({
  blast: Object.freeze({
    id: 'blast',
    name: '花火爆破',
    color: '#ffbc68',
    shape: 'circle',
    description: '指定圆形区域，0.55 秒后爆破，造成 130 点伤害并眩晕 0.8 秒。',
    radius: 125,
    range: 535,
    width: 0,
    duration: 0.95,
    delay: 0.55,
    damage: 130,
    stunDuration: 0.8,
    energyMax: 100,
  }),
  gale: Object.freeze({
    id: 'gale',
    name: '回旋大风',
    color: '#b7edda',
    shape: 'circle',
    description: '指定区域刮起大风，持续 1.2 秒造成伤害、向外推开敌人并短暂减速。',
    radius: 145,
    range: 510,
    width: 0,
    duration: 1.2,
    damagePerSecond: 34,
    pushSpeed: 210,
    slow: 0.4,
    slowDuration: 1.5,
    energyMax: 100,
  }),
  cart: Object.freeze({
    id: 'cart',
    name: '冲锋花车',
    color: '#e6b76b',
    shape: 'line',
    description: '向指定方向驶出花车，对路径上的敌人造成 115 点伤害并眩晕 1 秒。',
    radius: 32,
    range: 590,
    width: 64,
    duration: 0.82,
    speed: 760,
    damage: 115,
    stunDuration: 1,
    energyMax: 100,
  }),
  horse: Object.freeze({
    id: 'horse',
    name: '踏风战马',
    color: '#d1b4f7',
    shape: 'line',
    description: '战马沿指定方向冲锋，造成 95 点伤害，让命中的敌人恐惧后退 1.8 秒。',
    radius: 29,
    range: 620,
    width: 58,
    duration: 0.78,
    speed: 850,
    damage: 95,
    fearDuration: 1.8,
    energyMax: 100,
  }),
  laser: Object.freeze({
    id: 'laser',
    name: '日光射线',
    color: '#ffee97',
    shape: 'line',
    description: '沿指定方向发射光束，造成 100 点伤害，命中敌人随后 4 秒受到伤害增加 35%。',
    radius: 17,
    range: 640,
    width: 34,
    duration: 0.5,
    damage: 100,
    vulnerableDuration: 4,
    energyMax: 100,
  }),
});

export const UPGRADES = [
  {
    id: 'attack-power',
    name: '饱满弹芯',
    description: '普通子弹伤害 +25%。',
    category: 'weapon',
    maxRank: 5,
    weight: 1.2,
    kind: 'mushroom',
    icon: 'shot',
    effects: { damage: 0.25 },
  },
  {
    id: 'attack-speed',
    name: '疾风扳机',
    description: '自动射击频率 +18%。',
    category: 'weapon',
    maxRank: 4,
    weight: 1.2,
    kind: 'mushroom',
    icon: 'shot',
    effects: { fireRate: 0.18 },
  },
  {
    id: 'multishot',
    name: '花瓣散射',
    description: '每次射击多 1 发扇形子弹，单发伤害小幅降低。',
    category: 'weapon',
    maxRank: 2,
    weight: 0.75,
    kind: 'mushroom',
    icon: 'shot',
    effects: { projectiles: 1 },
  },
  {
    id: 'burst',
    name: '回声连击',
    description: '每轮射击追加 1 次短促连射，连射伤害为 65%。',
    category: 'weapon',
    maxRank: 2,
    weight: 0.8,
    kind: 'mushroom',
    icon: 'shot',
    effects: { burst: 1 },
  },
  {
    id: 'ricochet',
    name: '回旋弹道',
    description: '子弹碰到边界可多反弹 1 次并延长射程。反弹过的子弹不计打空。',
    category: 'weapon',
    maxRank: 3,
    weight: 0.8,
    kind: 'ice',
    icon: 'shot',
    effects: { bounces: 1 },
  },
  {
    id: 'ice-shot',
    name: '寒霜弹',
    description: '子弹使敌人减速 25%，持续 1.5 秒；每级再增强 10%。',
    category: 'weapon',
    maxRank: 3,
    weight: 1,
    kind: 'ice',
    icon: 'ice',
    effects: { chill: 1 },
  },
  {
    id: 'fire-shot',
    name: '灼热弹',
    description: '子弹附加燃烧，每秒造成 6 点伤害，持续 2 秒。',
    category: 'weapon',
    maxRank: 3,
    weight: 1,
    kind: 'mushroom',
    icon: 'shot',
    effects: { burn: 1 },
  },
  {
    id: 'explosive-shot',
    name: '爆裂弹',
    description: '主弹命中引发小范围爆炸，造成子弹伤害的 35%。',
    category: 'weapon',
    maxRank: 3,
    weight: 0.7,
    kind: 'mushroom',
    icon: 'mushroom',
    effects: { explosion: 0.35 },
  },
  {
    id: 'split-shot',
    name: '枝杈分裂',
    description: '主弹结束时分裂出 2 发短程碎片，伤害为主弹的 40%；每级多 1 发。',
    category: 'weapon',
    maxRank: 2,
    weight: 0.75,
    kind: 'thorn',
    icon: 'shot',
    effects: { split: 1 },
  },
  {
    id: 'split-explosion',
    name: '碎星花火',
    description: '分裂碎片命中时爆炸，造成碎片伤害的 40%，不会再次分裂。',
    category: 'weapon',
    maxRank: 2,
    requires: ['split-shot'],
    weight: 0.6,
    kind: 'mushroom',
    icon: 'mushroom',
    effects: { splitExplosion: 0.4 },
  },
  {
    id: 'wild-heart',
    name: '荒野之心',
    description: '生命上限 +25，恢复 40 生命，冲刺冷却缩短 0.3 秒。',
    category: 'survival',
    maxRank: 4,
    weight: 0.8,
    kind: 'ice',
    icon: 'heart',
    effects: { maxHp: 25, heal: 40, dashReduction: 0.3 },
  },
  ...Object.values(BOONS).map((boon) => ({
    id: `boon-${boon.id}`,
    name: `解锁 · ${boon.name}`,
    description: `解锁 · ${boon.description}`,
    category: 'terrain',
    unlockPlayerLevel: boon.unlockPlayerLevel ?? 1,
    maxRank: 1,
    weight: 1,
    kind: boon.kind,
    icon: boon.kind,
    effects: {},
  })),
  {
    id: 'terrain-heart',
    name: '繁茂花园',
    description: '强化 · 已解锁地形伤害 +25%，新地形范围 +10%。',
    category: 'terrain',
    maxRank: 4,
    weight: 1,
    kind: 'thorn',
    icon: 'thorn',
    effects: { terrainDamage: 0.25, terrainRadius: 0.1 },
  },
  {
    id: 'terrain-duration',
    name: '四季常青',
    description: '强化 · 已解锁地形持续时间 +25%。',
    category: 'terrain',
    maxRank: 3,
    weight: 1,
    kind: 'thorn',
    icon: 'leaf',
    effects: { terrainLife: 0.25 },
  },
  {
    id: 'sunflower-heart',
    name: '向阳花盘',
    description: '暖阳花治疗 +40%，治疗范围 +10%。',
    category: 'terrain',
    maxRank: 5,
    weight: 1,
    kind: 'sunflower',
    icon: 'sunflower',
    unlockPlayerLevel: 2,
    requires: ['boon-sunflower'],
    effects: { sunflowerHeal: 0.4, sunflowerRange: 0.1 },
  },
  {
    id: 'storm-heart',
    name: '雷枝交织',
    description: '引雷芦伤害 +35%，连锁范围 +15%。',
    category: 'terrain',
    maxRank: 5,
    weight: 1,
    kind: 'stormreed',
    icon: 'stormreed',
    unlockPlayerLevel: 4,
    requires: ['boon-stormreed'],
    effects: { stormDamage: 0.35, stormChainRange: 0.15 },
  },
  {
    id: 'turret-heart',
    name: '花瓣火线',
    description: '花瓣炮伤害 +30%，射击频率 +20%。',
    category: 'terrain',
    maxRank: 5,
    weight: 1,
    kind: 'bloomturret',
    icon: 'bloomturret',
    unlockPlayerLevel: 6,
    requires: ['boon-bloomturret'],
    effects: { turretDamage: 0.3, turretFireRate: 0.2 },
  },
  {
    id: 'energy-cycle',
    name: '能量涌动',
    description: '强化 · 时间与击杀获得的能量 +25%，两槽各补充 25 能量。',
    category: 'skill',
    maxRank: 3,
    weight: 0.8,
    kind: 'gale',
    icon: 'gale',
    effects: { energy: 0.25 },
  },
].map((upgrade) =>
  Object.freeze({
    ...upgrade,
    effects: Object.freeze(upgrade.effects),
    ...(upgrade.requires ? { requires: Object.freeze(upgrade.requires) } : {}),
  }),
);

// Weapon build entries share the XP upgrade catalogue; no duplicate effect registry.
export const WEAPONS = UPGRADES.filter((upgrade) => upgrade.category === 'weapon');
