/** Game-owned content and tuning; new levels reuse the same combat and growth rules. */
export const WORLD = Object.freeze({ width: 1440, height: 900 });

/** Automatic, temporary terrain. The historic SEEDS export names the garden species. */
export const SEEDS = Object.freeze({
  thorn: Object.freeze({
    id: 'thorn',
    name: '荆棘藤蔓',
    subtitle: '减速 · 持续伤害',
    description: '自动生长的荆棘持续 14 秒，敌人减速 58%，每秒受到 12 点伤害。',
    color: '#81da65',
    radius: 58,
    life: 14,
    health: 1,
    slow: 0.42,
    damagePerSecond: 12,
  }),
  ice: Object.freeze({
    id: 'ice',
    name: '寒冰柱',
    subtitle: '阻挡敌人 · 寒霜减速',
    description: '冰柱持续 12 秒，阻挡敌人并使附近敌人减速 25%；玩家可自由穿过。',
    color: '#67d4ff',
    radius: 28,
    life: 12,
    health: 105,
    auraRadius: 85,
    slow: 0.75,
  }),
  mushroom: Object.freeze({
    id: 'mushroom',
    name: '爆炸蘑菇',
    subtitle: '延迟 2.4 秒 · 范围爆炸',
    description: '蘑菇在 2.4 秒后爆炸，造成 105 点范围伤害，然后消失。',
    color: '#ffb34b',
    radius: 23,
    life: 2.4,
    health: 1,
    blastRadius: 124,
    blastDamage: 105,
  }),
});

export const ENEMIES = Object.freeze({
  sprout: Object.freeze({
    name: '芽怪',
    hp: 50,
    radius: 19,
    speed: 61,
    damage: 8,
    coins: 2,
    xp: 2,
    bite: 16,
  }),
  runner: Object.freeze({
    name: '疾行芽',
    hp: 34,
    radius: 14,
    speed: 114,
    damage: 6,
    coins: 3,
    xp: 3,
    bite: 11,
  }),
  brute: Object.freeze({
    name: '岩壳巨芽',
    hp: 178,
    radius: 33,
    speed: 43,
    damage: 16,
    coins: 8,
    xp: 8,
    bite: 39,
  }),
});

/** Effects are additive per rank; prerequisites list upgrade IDs that need one rank. */
export const UPGRADES = Object.freeze(
  [
    {
      id: 'attack-power',
      name: '饱满弹芯',
      description: '普通子弹伤害 +25%。',
      category: 'weapon',
      maxRank: 5,
      weight: 1.2,
      kind: 'mushroom',
      icon: 'shot',
      effects: { damage: 0.25 },
    },
    {
      id: 'attack-speed',
      name: '疾风扳机',
      description: '自动射击频率 +18%。',
      category: 'weapon',
      maxRank: 4,
      weight: 1.2,
      kind: 'mushroom',
      icon: 'shot',
      effects: { fireRate: 0.18 },
    },
    {
      id: 'multishot',
      name: '花瓣散射',
      description: '每次射击多 1 发扇形子弹，单发伤害小幅降低。',
      category: 'weapon',
      maxRank: 2,
      weight: 0.75,
      kind: 'mushroom',
      icon: 'shot',
      effects: { projectiles: 1 },
    },
    {
      id: 'burst',
      name: '回声连击',
      description: '每轮射击追加 1 次短促连射，连射伤害为 65%。',
      category: 'weapon',
      maxRank: 2,
      weight: 0.8,
      kind: 'mushroom',
      icon: 'shot',
      effects: { burst: 1 },
    },
    {
      id: 'ricochet',
      name: '回旋弹道',
      description: '子弹碰到边界可多反弹 1 次并延长射程。反弹过的子弹不计打空。',
      category: 'weapon',
      maxRank: 3,
      weight: 0.8,
      kind: 'ice',
      icon: 'shot',
      effects: { bounces: 1 },
    },
    {
      id: 'ice-shot',
      name: '寒霜弹',
      description: '子弹使敌人减速 25%，持续 1.5 秒；每级再增强 10%。',
      category: 'weapon',
      maxRank: 3,
      weight: 1,
      kind: 'ice',
      icon: 'ice',
      effects: { chill: 1 },
    },
    {
      id: 'fire-shot',
      name: '灼热弹',
      description: '子弹附加燃烧，每秒造成 6 点伤害，持续 2 秒。',
      category: 'weapon',
      maxRank: 3,
      weight: 1,
      kind: 'mushroom',
      icon: 'shot',
      effects: { burn: 1 },
    },
    {
      id: 'explosive-shot',
      name: '爆裂弹',
      description: '主弹命中引发小范围爆炸，造成子弹伤害的 35%。',
      category: 'weapon',
      maxRank: 3,
      weight: 0.7,
      kind: 'mushroom',
      icon: 'mushroom',
      effects: { explosion: 0.35 },
    },
    {
      id: 'split-shot',
      name: '枝杈分裂',
      description: '主弹结束时分裂出 2 发短程碎片，伤害为主弹的 40%；每级多 1 发。',
      category: 'weapon',
      maxRank: 2,
      weight: 0.75,
      kind: 'thorn',
      icon: 'shot',
      effects: { split: 1 },
    },
    {
      id: 'split-explosion',
      name: '碎星花火',
      description: '分裂碎片命中时爆炸，造成碎片伤害的 40%，不会再次分裂。',
      category: 'weapon',
      maxRank: 2,
      requires: ['split-shot'],
      weight: 0.6,
      kind: 'mushroom',
      icon: 'mushroom',
      effects: { splitExplosion: 0.4 },
    },
    {
      id: 'thorn-heart',
      name: '缠绕根系',
      description: '荆棘伤害 +40%，生长范围 +12%。',
      category: 'terrain',
      maxRank: 4,
      weight: 1,
      kind: 'thorn',
      icon: 'thorn',
      effects: { thornDamage: 0.4, thornRadius: 0.12 },
    },
    {
      id: 'ice-heart',
      name: '不融坚冰',
      description: '冰柱耐久 +50%，寒霜范围 +15%，减速再增强 5%。',
      category: 'terrain',
      maxRank: 3,
      weight: 1,
      kind: 'ice',
      icon: 'ice',
      effects: { iceHealth: 0.5, iceRadius: 0.15, iceSlow: 0.05 },
    },
    {
      id: 'mushroom-heart',
      name: '连锁菌群',
      description: '蘑菇爆炸伤害 +35%，爆炸范围 +12%。',
      category: 'terrain',
      maxRank: 4,
      weight: 1,
      kind: 'mushroom',
      icon: 'mushroom',
      effects: { mushroomDamage: 0.35, mushroomRadius: 0.12 },
    },
    {
      id: 'terrain-duration',
      name: '四季常青',
      description: '藤蔓和寒冰持续时间 +25%；蘑菇引爆时间保持不变。',
      category: 'terrain',
      maxRank: 3,
      weight: 1,
      kind: 'thorn',
      icon: 'leaf',
      effects: { terrainLife: 0.25 },
    },
    {
      id: 'seed-cycle',
      name: '丰收循环',
      description: '自动生长所需打空数 −1，最低 4 发。',
      category: 'terrain',
      maxRank: 2,
      weight: 0.8,
      kind: 'thorn',
      icon: 'leaf',
      effects: { missReduction: 1 },
    },
    {
      id: 'wild-heart',
      name: '荒野之心',
      description: '生命上限 +25，恢复 40 生命，冲刺冷却缩短 0.3 秒。',
      category: 'survival',
      maxRank: 4,
      weight: 0.8,
      kind: 'ice',
      icon: 'heart',
      effects: { maxHp: 25, heal: 40, dashReduction: 0.3 },
    },
  ].map((upgrade) =>
    Object.freeze({
      ...upgrade,
      effects: Object.freeze(upgrade.effects),
      ...(upgrade.requires ? { requires: Object.freeze(upgrade.requires) } : {}),
    }),
  ),
);

export const LEVELS = Object.freeze({
  ruins: Object.freeze({
    id: 'ruins',
    name: '失落庭院',
    subtitle: '第一章 · 在荒芜中盛放',
    duration: 300,
    waveDuration: 30,
    waves: 10,
    plantCap: 18,
    world: WORLD,
    bounds: Object.freeze({ left: 100, right: 1340, top: 150, bottom: 750 }),
    playerStart: Object.freeze({ x: 720, y: 470 }),
    growth: Object.freeze({
      missThreshold: 6,
      minimumThreshold: 4,
      triggerInterval: 1.25,
      minDistance: 140,
      maxDistance: 320,
      sector: Math.PI / 9,
      kinds: Object.freeze(['thorn', 'ice', 'mushroom']),
    }),
    progression: Object.freeze({
      firstXp: 12,
      xpStep: 10,
      fourChoicesAt: 5,
      upgradePool: Object.freeze(UPGRADES.map((upgrade) => upgrade.id)),
    }),
    spawn: Object.freeze({
      initialDelay: 1.4,
      interval: 1.8,
      acceleration: 0.14,
      minimumInterval: 0.54,
      maxEnemies: 48,
      composition: Object.freeze([
        { fromWave: 1, weights: { sprout: 1 } },
        { fromWave: 2, weights: { sprout: 0.62, runner: 0.38 } },
        { fromWave: 3, weights: { sprout: 0.55, runner: 0.27, brute: 0.18 } },
        { fromWave: 7, weights: { sprout: 0.4, runner: 0.36, brute: 0.24 } },
      ]),
    }),
  }),
});
