export type Candidate = { shapeId: string; color: number; stars?: [number, number][] };
export type Move = { slot: number; x: number; y: number };
export type GameState = {
  version: string; mode: 'level' | 'endless'; ranked?: boolean; levelId?: number; config?: Record<string, any>;
  board: number[]; starBoard: boolean[]; candidates: Candidate[]; used: number[];
  placedInGroup: number; group: number; completedGroups: number; score: number; combo: number;
  stats: Record<string, number>; status: 'playing' | 'won' | 'lost' | 'finished'; reason: string | null;
  undoRemaining: number; canUndo: boolean; stars: number; continued: boolean;
  rng?: number | { algorithm: string; key: string; counter: number }; lastEvent: Record<string, any> | null; [key: string]: any;
};
export const RULE_VERSION: string;
export const SHAPES_VERSION: string;
export const DIFFICULTY_VERSION: string;
export const SCORING_VERSION: string;
export const RANDOM_VERSION: string;
export const VERSION: Readonly<Record<string, string>>;
export const BOARD_SIZE: number;
export function createLevel(idOrConfig?: number | Record<string, any>): GameState;
export function createEndless(seed?: number | string, options?: { ranked?: boolean }): GameState;
export function place(state: GameState, slot: number, x: number, y: number): GameState;
export function placeIssuedGroup(state: GameState, slot: number, x: number, y: number): GameState;
export function undo(state: GameState): GameState;
export function canPlace(state: GameState, slot: number, x: number, y: number): boolean;
export function hasPlacement(state: GameState, slot?: number): boolean;
export function previewPlacement(state: GameState, slot: number, x: number, y: number): { valid: boolean; cells: number[]; rows: number[]; cols: number[]; lines: number };
export function getStars(state: GameState): number;
export function scoreForClear(lines: number, combo: number): number;
export function continueLevel(state: GameState, rewardId: string): GameState;
export function finishEndless(state: GameState): GameState;
export function replay(seed: number | string, moves: Move[], options?: { ranked?: boolean }): { ok: boolean; state: GameState; error?: string; invalidIndex?: number };
