/** Fifty authored arcade puzzles in five chapters; every gate begins closed.
 * Stable level IDs preserve saved progress. Solutions are verified shortest paths.
 */
export const LEVELS = [
  {
    id: 'first-link',
    title: '初次联动',
    chapter: '01 · 港口启航',
    maxMoves: 3,
    par: 1,
    intro: '打开 A—B，让两个房间分享水量。箱子落下的同时，小船也会升起。',
    tanks: [
      {
        id: 'A',
        name: '箱子间',
        volume: 8,
        kind: 'crate',
        switchAt: 4,
      },
      {
        id: 'B',
        name: '登船间',
        volume: 0,
        kind: 'boat',
        exitAt: 4,
      },
      {
        id: 'C',
        name: '储水间',
        volume: 4,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
    ],
    solution: ['AB'],
    requiresIsolation: false,
    design: '双槽平均同时完成落箱与升船；第三槽提供可选支路。',
  },
  {
    id: 'shared-level',
    title: '一阀，三室',
    chapter: '01 · 港口启航',
    maxMoves: 3,
    par: 2,
    intro: '先让箱子点亮 A 开关，再打开联锁阀。连通的三个房间会一起改变液位。',
    tanks: [
      {
        id: 'A',
        name: '机关间',
        volume: 10,
        kind: 'crate',
        switchAt: 5,
      },
      {
        id: 'B',
        name: '中转间',
        volume: 0,
        kind: 'reservoir',
      },
      {
        id: 'C',
        name: '出口间',
        volume: 2,
        kind: 'boat',
        exitAt: 4,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
        requires: 'A',
      },
    ],
    solution: ['AB', 'BC'],
    requiresIsolation: false,
    design: '箱子机关锁存后解锁末端阀；一阀令三个槽同时改变水位。',
  },
  {
    id: 'spill-chain',
    title: '溢流发电',
    chapter: '01 · 港口启航',
    maxMoves: 3,
    par: 1,
    intro: 'B 的溢流口在第 4 格。分享液位后，多出的水会推动水轮，再托起下游的小船。',
    tanks: [
      {
        id: 'A',
        name: '机关间',
        volume: 10,
        kind: 'crate',
        switchAt: 4,
      },
      {
        id: 'B',
        name: '水轮间',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '下游港',
        volume: 1,
        kind: 'boat',
        exitAt: 3,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'C',
        at: 4,
        powerNeeded: 2,
      },
    ],
    solution: ['AB'],
    requiresIsolation: false,
    design: '首次开阀同时触发箱子、水轮和小船三个目标。',
  },
  {
    id: 'keep-the-water',
    title: '留住那格水',
    chapter: '01 · 港口启航',
    maxMoves: 5,
    par: 3,
    intro: '开关点亮后会一直保持。先降低 A，再关阀隔离它，把右边的水留给小船。',
    tanks: [
      {
        id: 'A',
        name: '箱子间',
        volume: 8,
        kind: 'crate',
        switchAt: 4,
      },
      {
        id: 'B',
        name: '升船间',
        volume: 0,
        kind: 'boat',
        exitAt: 7,
      },
      {
        id: 'C',
        name: '高水仓',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
    ],
    solution: ['AB', 'AB', 'BC'],
    requiresIsolation: true,
    design: '先点亮机关，再隔离它，让高水仓仅补给小船。',
  },
  {
    id: 'three-room-drawdown',
    title: '先降，再升',
    chapter: '01 · 港口启航',
    maxMoves: 6,
    par: 4,
    intro: '两个房间还不够低。借第三间压下箱子，再隔离中转区，让高水仓只托举小船。',
    tanks: [
      {
        id: 'A',
        name: '低位开关',
        volume: 8,
        kind: 'crate',
        switchAt: 3,
      },
      {
        id: 'B',
        name: '中转间',
        volume: 0,
        kind: 'reservoir',
      },
      {
        id: 'C',
        name: '升船间',
        volume: 1,
        kind: 'boat',
        exitAt: 6.5,
      },
      {
        id: 'D',
        name: '高水仓',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
        requires: 'A',
      },
    ],
    solution: ['AB', 'BC', 'BC', 'CD'],
    requiresIsolation: true,
    design: '三槽共同降水触发低机关，再隔离船舱支路补高。',
  },
  {
    id: 'two-crate-relay',
    title: '双箱接力',
    chapter: '01 · 港口启航',
    maxMoves: 6,
    par: 4,
    intro: '两盏机关灯都要点亮。完成 C 的任务后，关上 C—D，才能把小船送到更高的平台。',
    tanks: [
      {
        id: 'A',
        name: '左机关间',
        volume: 8,
        kind: 'crate',
        switchAt: 4,
      },
      {
        id: 'B',
        name: '缓冲间',
        volume: 0,
        kind: 'reservoir',
      },
      {
        id: 'C',
        name: '右机关间',
        volume: 6,
        kind: 'crate',
        switchAt: 3,
      },
      {
        id: 'D',
        name: '升船间',
        volume: 0,
        kind: 'boat',
        exitAt: 6.5,
      },
      {
        id: 'E',
        name: '高水仓',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
        requires: 'A',
      },
    ],
    solution: ['AB', 'CD', 'CD', 'DE'],
    requiresIsolation: true,
    design: '两个独立落箱任务合并成末端升船接力。',
  },
  {
    id: 'spill-isolation',
    title: '关阀，才有落差',
    chapter: '01 · 港口启航',
    maxMoves: 6,
    par: 4,
    intro: '先借船舱降低 A。B 和 C 连通时不会溢流；关上它们之间的阀门，水轮才会转起来。',
    tanks: [
      {
        id: 'A',
        name: '深位开关',
        volume: 8,
        kind: 'crate',
        switchAt: 2.7,
      },
      {
        id: 'B',
        name: '水轮间',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '下游港',
        volume: 0,
        kind: 'boat',
        exitAt: 9,
      },
      {
        id: 'D',
        name: '高水仓',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
        requires: 'A',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'C',
        at: 3,
        powerNeeded: 6,
      },
    ],
    solution: ['AB', 'BC', 'BC', 'BD'],
    requiresIsolation: true,
    design: '下游与上游连通时禁止溢流；隔离后高水形成有效落差。',
  },
  {
    id: 'station-symphony',
    title: '全站协奏',
    chapter: '01 · 港口启航',
    maxMoves: 7,
    par: 5,
    intro: '先点亮低位 A，再用溢流点亮 C，最后释放高水仓。两个开关、水轮和小船，一次全站联动。',
    tanks: [
      {
        id: 'A',
        name: '低位机关',
        volume: 8,
        kind: 'crate',
        switchAt: 2.7,
      },
      {
        id: 'B',
        name: '水轮间',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '联锁机关',
        volume: 8,
        kind: 'crate',
        switchAt: 3,
      },
      {
        id: 'D',
        name: '最终出口',
        volume: 0,
        kind: 'boat',
        exitAt: 9.5,
      },
      {
        id: 'E',
        name: '高水仓',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
        requires: 'A',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
        requires: 'C',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'D',
        at: 3,
        powerNeeded: 7,
      },
    ],
    solution: ['AB', 'BD', 'BD', 'BC', 'CE'],
    requiresIsolation: true,
    design: '两机关依次解锁，单向溢流与共享液位共同完成全站目标。',
  },
  {
    id: 'boat-first',
    title: '先送船，再落箱',
    chapter: '01 · 港口启航',
    maxMoves: 4,
    par: 3,
    intro: '先把 C 船送到平台，关阀留住船舱水位，再借 A 降低 B。',
    tanks: [
      {
        id: 'A',
        name: '低水池',
        kind: 'reservoir',
        volume: 1,
      },
      {
        id: 'B',
        name: '中央机关',
        kind: 'crate',
        volume: 8,
        switchAt: 3,
      },
      {
        id: 'C',
        name: '候船舱',
        kind: 'boat',
        volume: 2,
        exitAt: 4.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
    ],
    solution: ['BC', 'BC', 'AB'],
    requiresIsolation: true,
    design: '把传统先落箱后升船的顺序倒过来：先完成出口，隔离已达标的船，再抽低中央机关。',
  },
  {
    id: 'twin-harbor',
    title: '双港会合',
    chapter: '01 · 港口启航',
    maxMoves: 4,
    par: 3,
    intro: '两艘船都要抵达平台。B 机关点亮后，再接通右侧高水仓。',
    tanks: [
      {
        id: 'A',
        name: '左港',
        kind: 'boat',
        volume: 3,
        exitAt: 5,
      },
      {
        id: 'B',
        name: '联锁机关',
        kind: 'crate',
        volume: 7,
        switchAt: 4,
      },
      {
        id: 'C',
        name: '右港',
        kind: 'boat',
        volume: 0,
        exitAt: 5,
      },
      {
        id: 'D',
        name: '补水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
        requires: 'B',
      },
    ],
    solution: ['AB', 'BC', 'CD'],
    requiresIsolation: false,
    design: '四槽长链带双船；中途两船液位会下降，利用锁存机关解锁末端水源后一并抬升。',
  },
  {
    id: 'harbor-junction',
    title: '三岔中转',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: '先借 D 降低 B，隔离机关舱，再把 C 的水送往出口。',
    tanks: [
      {
        id: 'A',
        name: '中转池',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'B',
        name: '箱子机关',
        kind: 'crate',
        volume: 10,
        switchAt: 4,
      },
      {
        id: 'C',
        name: '高位水仓',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'D',
        name: '升船舱',
        kind: 'boat',
        volume: 2,
        exitAt: 6,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
    ],
    solution: ['AB', 'AD', 'AB', 'AC'],
    requiresIsolation: true,
    design: '以空中转槽为三叉中心；先接机关和船降低开关，再切走机关，留下中心与船接受高水。',
  },
  {
    id: 'double-berth',
    title: '双船双箱',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: '左右先各自分享水量；右箱落下后，保留它的低水位，再联通中央。',
    tanks: [
      {
        id: 'A',
        name: '左船坞',
        kind: 'boat',
        volume: 2,
        exitAt: 4.5,
      },
      {
        id: 'B',
        name: '左箱室',
        kind: 'crate',
        volume: 8,
        switchAt: 4.5,
      },
      {
        id: 'C',
        name: '右船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 4.5,
      },
      {
        id: 'D',
        name: '右箱室',
        kind: 'crate',
        volume: 7,
        switchAt: 3.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
    ],
    solution: ['AB', 'CD', 'CD', 'BC'],
    requiresIsolation: true,
    design: '四槽长链全部承担目标，两端小船和两个箱子通过分组与合组先后达标。',
  },
  {
    id: 'third-room-buffer',
    title: '第三间缓冲',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: 'B 还差一点才能压下机关。借 D 缓冲，然后关上缓冲口再补水。',
    tanks: [
      {
        id: 'A',
        name: '补水仓',
        kind: 'reservoir',
        volume: 9,
      },
      {
        id: 'B',
        name: '低位机关',
        kind: 'crate',
        volume: 6,
        switchAt: 3,
      },
      {
        id: 'C',
        name: '升船舱',
        kind: 'boat',
        volume: 1,
        exitAt: 5,
      },
      {
        id: 'D',
        name: '缓冲仓',
        kind: 'reservoir',
        volume: 2,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
    ],
    solution: ['BC', 'CD', 'CD', 'AB'],
    requiresIsolation: true,
    design: '中部箱子与船的两槽平均值不足以触发开关；第三槽参与降水，隔离后从另一端灌入高水。',
  },
  {
    id: 'borrow-and-return',
    title: '先借后还',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: '把 C 暂时当储水池。A 点亮后，再让存下的水回到三个房间。',
    tanks: [
      {
        id: 'A',
        name: '主机关',
        kind: 'crate',
        volume: 10,
        switchAt: 3.5,
      },
      {
        id: 'B',
        name: '小船舱',
        kind: 'boat',
        volume: 1,
        exitAt: 4,
      },
      {
        id: 'C',
        name: '临时水仓',
        kind: 'reservoir',
        volume: 2,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
    ],
    solution: ['AC', 'AC', 'AB', 'AC'],
    requiresIsolation: true,
    design: '三槽两阀需要同一蓄水支路开、关、再开；分批均水先落箱，再返还储水托举小船。',
  },
  {
    id: 'branch-lights',
    title: '支流点灯',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: '先点亮 D，再点亮 C。两盏灯会记住低水位，最后才释放 E。',
    tanks: [
      {
        id: 'A',
        name: '空水池',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'B',
        name: '中心船坞',
        kind: 'boat',
        volume: 1,
        exitAt: 5,
      },
      {
        id: 'C',
        name: '上游机关',
        kind: 'crate',
        volume: 8,
        switchAt: 4.5,
      },
      {
        id: 'D',
        name: '支流机关',
        kind: 'crate',
        volume: 6,
        switchAt: 2.5,
      },
      {
        id: 'E',
        name: '末端水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['AB', 'BD', 'BC', 'DE'],
    requiresIsolation: false,
    design: '五槽T形支流的两个箱子阈值不同，必须让低阈值机关先加入共享池，再接第二机关和末端水源。',
  },
  {
    id: 'key-before-key',
    title: '钥匙的钥匙',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: '先借 D、E 降低 B，解锁 A 的接入口；两个箱子都落下后再接 C。',
    tanks: [
      {
        id: 'A',
        name: '后级机关',
        kind: 'crate',
        volume: 7,
        switchAt: 4.5,
      },
      {
        id: 'B',
        name: '前级机关',
        kind: 'crate',
        volume: 7,
        switchAt: 3.5,
      },
      {
        id: 'C',
        name: '高水仓',
        kind: 'reservoir',
        volume: 9,
      },
      {
        id: 'D',
        name: '中央船坞',
        kind: 'boat',
        volume: 1,
        exitAt: 4.5,
      },
      {
        id: 'E',
        name: '低水仓',
        kind: 'reservoir',
        volume: 2,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
        requires: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['BD', 'DE', 'AB', 'BC'],
    requiresIsolation: false,
    design: '第一个机关解锁第二个机关所在支路；两箱锁存允许最后引入高水源，五槽一齐升至出口。',
  },
  {
    id: 'sail-and-seal',
    title: '靠岸封舱',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: 'C、D 分享的水足以送船。封住 B—C 后，再让 A 接住机关舱的水。',
    tanks: [
      {
        id: 'A',
        name: '接水池',
        kind: 'reservoir',
        volume: 1,
      },
      {
        id: 'B',
        name: '箱子机关',
        kind: 'crate',
        volume: 10,
        switchAt: 4.5,
      },
      {
        id: 'C',
        name: '船坞前池',
        kind: 'reservoir',
        volume: 2,
      },
      {
        id: 'D',
        name: '末端出口',
        kind: 'boat',
        volume: 3,
        exitAt: 5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
    ],
    solution: ['BC', 'CD', 'BC', 'AB'],
    requiresIsolation: true,
    design: '船在长链右端，机关在左中；先整体送船，再在链中切断，把目标水位保留在右侧分量。',
  },
  {
    id: 'two-boat-lift',
    title: '两船共升',
    chapter: '02 · 分舱实验站',
    maxMoves: 5,
    par: 4,
    intro: '两艘船先一起借水压下 D；机关完成后，把 D 隔离再接高水仓。',
    tanks: [
      {
        id: 'A',
        name: '中心船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 4,
      },
      {
        id: 'B',
        name: '高水仓',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'C',
        name: '外侧船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 5,
      },
      {
        id: 'D',
        name: '箱子机关',
        kind: 'crate',
        volume: 8,
        switchAt: 3,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
    ],
    solution: ['AC', 'AD', 'AD', 'AB'],
    requiresIsolation: true,
    design: '双船共同作为降水容积，机关与高水源分别占据星形另两枝；同一中心完成降水和补水。',
  },
  {
    id: 'seal-both-arms',
    title: '封住两条臂',
    chapter: '02 · 分舱实验站',
    maxMoves: 6,
    par: 5,
    intro: '先将 C 送到出口，再关上两条已充水的支路，把 A 剩下的水分给 D。',
    tanks: [
      {
        id: 'A',
        name: '分配机关',
        kind: 'crate',
        volume: 9,
        switchAt: 3.5,
      },
      {
        id: 'B',
        name: '蓄水臂',
        kind: 'reservoir',
        volume: 8,
      },
      {
        id: 'C',
        name: '出口臂',
        kind: 'boat',
        volume: 0,
        exitAt: 5.5,
      },
      {
        id: 'D',
        name: '接水臂',
        kind: 'reservoir',
        volume: 1,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
    ],
    solution: ['AB', 'AC', 'AB', 'AC', 'AD'],
    requiresIsolation: true,
    design: '星形机关中心先从高水枝借水送船，再必须关闭两条支路，借低水枝单独压下中心箱子。',
  },
  {
    id: 'relay-away',
    title: '接力向远方',
    chapter: '02 · 分舱实验站',
    maxMoves: 6,
    par: 5,
    intro: 'A 完成任务后能继续涨水。保住左侧船坞，再让 C 借右边两间降水。',
    tanks: [
      {
        id: 'A',
        name: '先行机关',
        kind: 'crate',
        volume: 8,
        switchAt: 4,
      },
      {
        id: 'B',
        name: '左侧船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 5.5,
      },
      {
        id: 'C',
        name: '接力机关',
        kind: 'crate',
        volume: 9,
        switchAt: 3.5,
      },
      {
        id: 'D',
        name: '第一缓冲',
        kind: 'reservoir',
        volume: 2,
      },
      {
        id: 'E',
        name: '第二缓冲',
        kind: 'reservoir',
        volume: 2,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['AB', 'BC', 'BC', 'CD', 'DE'],
    requiresIsolation: true,
    design: '两机关夹住船；先触发左箱，再从右箱向船补水，关闭中段后让右箱在两槽支流中完成任务。',
  },
  {
    id: 'close-the-loop',
    title: '隔离两路',
    chapter: '03 · 支流调度港',
    maxMoves: 6,
    par: 5,
    intro: '借两个低水房间压下 D，关上两条低水支路，最后打开带锁的高水阀。',
    tanks: [
      {
        id: 'A',
        name: '中心船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 5.5,
      },
      {
        id: 'B',
        name: '低位水池',
        kind: 'reservoir',
        volume: 1,
      },
      {
        id: 'C',
        name: '锁定水仓',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'D',
        name: '解锁机关',
        kind: 'crate',
        volume: 6,
        switchAt: 2.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
        requires: 'D',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
    ],
    solution: ['AB', 'AD', 'AB', 'AD', 'AC'],
    requiresIsolation: true,
    design: '三叉船舱中心需要同时切断两个泄水分支，高水源受机关锁保护；少关任一枝都到不了高出口。',
  },
  {
    id: 'forked-relay',
    title: '岔路接力',
    chapter: '03 · 支流调度港',
    maxMoves: 6,
    par: 5,
    intro: 'A 点亮后先退出共享液位，再把 C 接入；最后让空仓 E 吸收多余水。',
    tanks: [
      {
        id: 'A',
        name: '左侧机关',
        kind: 'crate',
        volume: 6,
        switchAt: 3,
      },
      {
        id: 'B',
        name: '转运间',
        kind: 'reservoir',
        volume: 1,
      },
      {
        id: 'C',
        name: '右侧机关',
        kind: 'crate',
        volume: 10,
        switchAt: 4,
      },
      {
        id: 'D',
        name: '分支船坞',
        kind: 'boat',
        volume: 2,
        exitAt: 4,
      },
      {
        id: 'E',
        name: '空水仓',
        kind: 'reservoir',
        volume: 0,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['AB', 'BD', 'AB', 'BC', 'DE'],
    requiresIsolation: true,
    design: '五槽T形的两个机关分居枝端；A必须先锁存并隔离，末端空仓再将C降到阈值而船仍达出口。',
  },
  {
    id: 'ring-relay-lock',
    title: '环线接力锁',
    chapter: '03 · 支流调度港',
    maxMoves: 7,
    par: 6,
    intro: '先经 B 压下 C、解锁回环；把水量分开暂存，再让 D 从另一侧托起船。',
    tanks: [
      {
        id: 'A',
        name: '环线船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 4,
      },
      {
        id: 'B',
        name: '接水前池',
        kind: 'reservoir',
        volume: 1,
      },
      {
        id: 'C',
        name: '回环钥匙',
        kind: 'crate',
        volume: 10,
        switchAt: 4.5,
      },
      {
        id: 'D',
        name: '接力箱室',
        kind: 'crate',
        volume: 8,
        switchAt: 4.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DA',
        a: 'D',
        b: 'A',
        requires: 'C',
      },
    ],
    solution: ['AB', 'BC', 'AB', 'CD', 'CD', 'DA'],
    requiresIsolation: true,
    design:
      '四槽闭环让同一船可以从两侧收水。先走三槽低水路径解锁回边，中途两次隔离调整D的供水量，最终D落箱同时A升船。',
  },
  {
    id: 'ring-twin-docks',
    title: '环线双船坞',
    chapter: '03 · 支流调度港',
    maxMoves: 7,
    par: 6,
    intro: '先照顾 B 的高平台，再用 D 压下 C。隔离机关后，两船从 A 同时补水。',
    tanks: [
      {
        id: 'A',
        name: '高水中转',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'B',
        name: '高位船坞',
        kind: 'boat',
        volume: 2,
        exitAt: 5.5,
      },
      {
        id: 'C',
        name: '低位机关',
        kind: 'crate',
        volume: 6,
        switchAt: 3,
      },
      {
        id: 'D',
        name: '环外船坞',
        kind: 'boat',
        volume: 2,
        exitAt: 4.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DA',
        a: 'D',
        b: 'A',
      },
    ],
    solution: ['BC', 'BC', 'AB', 'CD', 'CD', 'DA'],
    requiresIsolation: true,
    design:
      '四槽环形双船两目标不同；先从机关分水给B并补高，再让C向D降水，最后从环的另一侧将两船接入同一高水分量。',
  },
  {
    id: 'latch-and-hold',
    title: '点灯与留水',
    chapter: '03 · 支流调度港',
    maxMoves: 6,
    par: 5,
    intro: 'B 点亮后才能接 C。船到平台就关上船阀，再用 E 点亮第二盏灯。',
    tanks: [
      {
        id: 'A',
        name: '中央水池',
        kind: 'reservoir',
        volume: 2,
      },
      {
        id: 'B',
        name: '第一机关',
        kind: 'crate',
        volume: 9,
        switchAt: 4.5,
      },
      {
        id: 'C',
        name: '第二机关',
        kind: 'crate',
        volume: 7,
        switchAt: 4.5,
      },
      {
        id: 'D',
        name: '独立船坞',
        kind: 'boat',
        volume: 2,
        exitAt: 5,
      },
      {
        id: 'E',
        name: '空置水仓',
        kind: 'reservoir',
        volume: 0,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
        requires: 'B',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
      {
        id: 'AE',
        a: 'A',
        b: 'E',
      },
    ],
    solution: ['AB', 'AD', 'AC', 'AD', 'AE'],
    requiresIsolation: true,
    design:
      '五星中心依次连接两个机关，一个机关为另一个解锁；船从两箱获得水后封存，中心余水向空仓降低第二箱。',
  },
  {
    id: 'two-small-sips',
    title: '分两口借水',
    chapter: '03 · 支流调度港',
    maxMoves: 6,
    par: 5,
    intro: '先借 B 的一部分水，再让 A 向 C 放水。隔离 C 后，再向 B 借一次。',
    tanks: [
      {
        id: 'A',
        name: '中心船坞',
        kind: 'boat',
        volume: 3,
        exitAt: 4,
      },
      {
        id: 'B',
        name: '高水机关',
        kind: 'crate',
        volume: 8,
        switchAt: 4.5,
      },
      {
        id: 'C',
        name: '空置水池',
        kind: 'reservoir',
        volume: 0,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
    ],
    solution: ['AB', 'AB', 'AC', 'AC', 'AB'],
    requiresIsolation: true,
    design:
      '仅三个槽的二次均水谜题，同一机关供水两次；空槽先接走一份水使第二次平均水位同时满足箱子与船。',
  },
  {
    id: 'crate-spillway',
    title: '箱舱泄洪',
    chapter: '03 · 支流调度港',
    maxMoves: 6,
    par: 4,
    intro: '箱子舱也有溢流口。先让三舱分享水量，再隔离出口迎接高仓。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 3.5,
        kind: 'crate',
        switchAt: 3.2,
      },
      {
        id: 'B',
        name: '储水罐',
        volume: 6,
        kind: 'reservoir',
      },
      {
        id: 'C',
        name: '出口泊位',
        volume: 0,
        kind: 'boat',
        exitAt: 7.5,
      },
      {
        id: 'D',
        name: '储水罐',
        volume: 9,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
        requires: 'A',
      },
    ],
    overflow: [
      {
        from: 'A',
        to: 'C',
        at: 3.5,
        powerNeeded: 3,
      },
    ],
    solution: ['AB', 'BC', 'BC', 'AD'],
    requiresIsolation: true,
    design:
      '溢流源直接设在箱子舱 A。A—B 首次分享水量会先溢流，但箱子仍未触发；接入 C 后锁灯，再关 B—C 并开 A—D，将三舱余量集中送船。',
  },
  {
    id: 'two-crate-feed',
    title: '双箱助推',
    chapter: '03 · 支流调度港',
    maxMoves: 6,
    par: 4,
    intro: '第一只箱子落下后，把它留在原位。第二个箱子舱会接过补水任务。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        kind: 'crate',
        volume: 6,
        switchAt: 4,
      },
      {
        id: 'B',
        name: '水轮舱',
        kind: 'wheel',
        volume: 0,
      },
      {
        id: 'C',
        name: '机关舱',
        kind: 'crate',
        volume: 8,
        switchAt: 4,
      },
      {
        id: 'D',
        name: '出口泊位',
        kind: 'boat',
        volume: 0,
        exitAt: 5,
      },
      {
        id: 'E',
        name: '储水罐',
        kind: 'reservoir',
        volume: 6,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
        requires: 'A',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: 'C',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'D',
        at: 4,
        powerNeeded: 2,
      },
    ],
    solution: ['AB', 'AB', 'BC', 'CE'],
    requiresIsolation: true,
    design:
      'A—B 点亮 A 后必须关闭，避免 A 分走水；开 B—C 的溢流恰好点亮 C，继续接 C—E 会经 B 的溢流口完成升船。D—E 双向连通是额外选择，不能替代溢流供水。',
  },
  {
    id: 'cascade-reserve',
    title: '双级蓄潮',
    chapter: '03 · 支流调度港',
    maxMoves: 7,
    par: 5,
    intro: '两级溢流要接力。高仓放水后，再让左侧余水送小船最后一程。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 10,
        kind: 'crate',
        switchAt: 3.5,
      },
      {
        id: 'B',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'D',
        name: '出口泊位',
        volume: 0,
        kind: 'boat',
        exitAt: 7.5,
      },
      {
        id: 'E',
        name: '储水罐',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
        requires: 'A',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'C',
        at: 2.5,
        powerNeeded: 4,
      },
      {
        from: 'C',
        to: 'D',
        at: 4,
        powerNeeded: 2,
      },
    ],
    solution: ['AB', 'CE', 'BC', 'CE', 'BC'],
    requiresIsolation: true,
    design:
      '首轮 A—B 同时触发两级溢流并点亮机关；C—E 首次放水尚差半格。需要短暂合并上游重新分水，先隔离高仓，再隔离两级水轮，释放左侧余量。',
  },
  {
    id: 'full-dock-buffer',
    title: '满仓蓄势',
    chapter: '03 · 支流调度港',
    maxMoves: 7,
    par: 5,
    intro: '高水泊位挡住了落水。先连通暂存，再关阀形成落差，最后把水分给出口。',
    tanks: [
      {
        id: 'A',
        name: '储水罐',
        volume: 9,
        kind: 'reservoir',
      },
      {
        id: 'B',
        name: '储水罐',
        volume: 0,
        kind: 'reservoir',
      },
      {
        id: 'C',
        name: '机关舱',
        volume: 4.5,
        kind: 'crate',
        switchAt: 3,
      },
      {
        id: 'D',
        name: '储水罐',
        volume: 9,
        kind: 'reservoir',
      },
      {
        id: 'E',
        name: '出口泊位',
        volume: 1,
        kind: 'boat',
        exitAt: 5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: 'C',
      },
    ],
    overflow: [
      {
        from: 'C',
        to: 'D',
        at: 4.5,
        powerNeeded: 1,
      },
    ],
    solution: ['BC', 'AB', 'BD', 'BD', 'DE'],
    requiresIsolation: true,
    design:
      '下游 D 初始九格，限制了溢流。C 先借 B 点亮机关；A—B 补水后接 B—D 让满仓参与平衡，随后切断产生 3.375 格溢流动力，最后开 D—E 升船。',
  },
  {
    id: 'cascade-separation',
    title: '分段落差',
    chapter: '04 · 溢流动力站',
    maxMoves: 8,
    par: 6,
    intro: '先借四个舱降低箱子，再分开两级水轮，让最后一段落差托起小船。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 9,
        kind: 'crate',
        switchAt: 2.5,
      },
      {
        id: 'B',
        name: '水轮舱',
        volume: 1,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'D',
        name: '出口泊位',
        volume: 0,
        kind: 'boat',
        exitAt: 5,
      },
      {
        id: 'E',
        name: '储水罐',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'AE',
        a: 'A',
        b: 'E',
        requires: 'A',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'C',
        at: 3.5,
        powerNeeded: 1,
      },
      {
        from: 'C',
        to: 'D',
        at: 4.5,
        powerNeeded: 3,
      },
    ],
    solution: ['AB', 'BC', 'CD', 'BC', 'AE', 'CD'],
    requiresIsolation: true,
    design:
      '四舱均衡至 2.5 解锁 A—E；需先关闭 B—C，让补水流向 C—D 的下游组，再关闭 C—D，产生第二级溢流。',
  },
  {
    id: 'borrow-downstream',
    title: '先借下游',
    chapter: '04 · 溢流动力站',
    maxMoves: 8,
    par: 6,
    intro: '出口舱也能暂借给箱子。归还下游空间后，再放开高仓。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 8,
        kind: 'crate',
        switchAt: 2,
      },
      {
        id: 'B',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'D',
        name: '出口泊位',
        volume: 2,
        kind: 'boat',
        exitAt: 7,
      },
      {
        id: 'E',
        name: '储水罐',
        volume: 9,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
      {
        id: 'BE',
        a: 'B',
        b: 'E',
        requires: 'A',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'C',
        at: 3,
        powerNeeded: 2,
      },
      {
        from: 'C',
        to: 'D',
        at: 2.5,
        powerNeeded: 4,
      },
    ],
    solution: ['AD', 'CD', 'AD', 'AB', 'CD', 'BE'],
    requiresIsolation: true,
    design:
      '先用 A—D、C—D 借下游缓冲空间，再隔离 A 并打开 A—B 压下低位机关；关闭 C—D 才能让后续 B→C→D 双级溢流集中抬船。',
  },
  {
    id: 'side-buffer',
    title: '旁仓低位',
    chapter: '04 · 溢流动力站',
    maxMoves: 8,
    par: 6,
    intro: '空旁仓能帮箱子再降一次。把两个缓冲区分开，保留水轮的启动水量。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 10,
        kind: 'crate',
        switchAt: 2,
      },
      {
        id: 'B',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '出口泊位',
        volume: 0,
        kind: 'boat',
        exitAt: 4.5,
      },
      {
        id: 'D',
        name: '储水罐',
        volume: 0,
        kind: 'reservoir',
      },
      {
        id: 'E',
        name: '储水罐',
        volume: 6,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BE',
        a: 'B',
        b: 'E',
        requires: 'A',
      },
      {
        id: 'AD',
        a: 'A',
        b: 'D',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'C',
        at: 4,
        powerNeeded: 3,
      },
    ],
    solution: ['AB', 'BC', 'AB', 'BC', 'AD', 'BE'],
    requiresIsolation: true,
    design:
      '水轮首轮溢流不足以通关；三舱共享后需分别切断 A—B 与 B—C，再接 A 的空旁仓 D 完成低位开关。这样 B 的水量得以保留，与 E 的六格水形成最后溢流。',
  },
  {
    id: 'two-lock-transfer',
    title: '双锁换舱',
    chapter: '04 · 溢流动力站',
    maxMoves: 8,
    par: 6,
    intro: '两只箱子要依次落下。借船舱点亮第二盏灯，再把它隔离等待放水。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        kind: 'crate',
        volume: 10,
        switchAt: 4,
      },
      {
        id: 'B',
        name: '储水罐',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'C',
        name: '机关舱',
        kind: 'crate',
        volume: 4,
        switchAt: 3.5,
      },
      {
        id: 'D',
        name: '出口泊位',
        kind: 'boat',
        volume: 0,
        exitAt: 5,
      },
      {
        id: 'E',
        name: '储水罐',
        kind: 'reservoir',
        volume: 6,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
        requires: 'A',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
        requires: 'C',
      },
    ],
    overflow: [
      {
        from: 'C',
        to: 'D',
        at: 4,
        powerNeeded: 3,
      },
    ],
    solution: ['AB', 'BC', 'BD', 'BC', 'BD', 'CE'],
    requiresIsolation: true,
    design:
      'A 的开关控制 B—D，C 的开关控制 C—E。先通过 C 的溢流点亮 A，再连接船舱降低 C；分别隔离 C 与 D 后放开高仓，才能把船送到五格。',
  },
  {
    id: 'two-port-split',
    title: '两港分水',
    chapter: '04 · 溢流动力站',
    maxMoves: 8,
    par: 6,
    intro: '两艘船都要到站。先照顾右港，再隔离它，把剩余水送给水轮。',
    tanks: [
      {
        id: 'A',
        name: '储水罐',
        kind: 'reservoir',
        volume: 6,
      },
      {
        id: 'B',
        name: '水轮舱',
        kind: 'wheel',
        volume: 1,
      },
      {
        id: 'C',
        name: '储水罐',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'D',
        name: '出口泊位',
        kind: 'boat',
        volume: 0,
        exitAt: 7,
      },
      {
        id: 'E',
        name: '出口泊位',
        kind: 'boat',
        volume: 0,
        exitAt: 4,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'D',
        at: 2,
        powerNeeded: 4,
      },
    ],
    solution: ['AB', 'AB', 'AC', 'CE', 'CE', 'AB'],
    requiresIsolation: true,
    design:
      '没有箱子锁的双船纯分水关。初次溢流为 D 打底；隔离 A—B，A—C 接高仓，C—E 托起 E 至四格后关闭，最后重连 A—B 把剩水溢流送 D。',
  },
  {
    id: 'return-reserve',
    title: '回灌余量',
    chapter: '04 · 溢流动力站',
    maxMoves: 9,
    par: 7,
    intro: '点亮开关只是第一步。借出口侧的余水回灌，才够水轮完成最后一转。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 7,
        kind: 'crate',
        switchAt: 2.5,
      },
      {
        id: 'B',
        name: '储水罐',
        volume: 8,
        kind: 'reservoir',
      },
      {
        id: 'C',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'D',
        name: '出口泊位',
        volume: 0,
        kind: 'boat',
        exitAt: 5.5,
      },
      {
        id: 'E',
        name: '储水罐',
        volume: 10,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'AC',
        a: 'A',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
        requires: 'A',
      },
    ],
    overflow: [
      {
        from: 'C',
        to: 'D',
        at: 4.5,
        powerNeeded: 4,
      },
    ],
    solution: ['AB', 'BD', 'AB', 'AC', 'AB', 'AB', 'CE'],
    requiresIsolation: true,
    design:
      'A、B、D 先共享，A 再隔离并借空 C 下调至 2.5；直接开高仓不足以满足轮机累计目标。需重连 A—B 回收右侧水量，隔离后再放开 C—E。',
  },
  {
    id: 'drain-transfer',
    title: '预放中转',
    chapter: '04 · 溢流动力站',
    maxMoves: 9,
    par: 7,
    intro: '中转舱先给小船一点水，再留作空位，帮助箱子解锁高仓。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        volume: 6,
        kind: 'crate',
        switchAt: 2.5,
      },
      {
        id: 'B',
        name: '水轮舱',
        volume: 0,
        kind: 'wheel',
      },
      {
        id: 'C',
        name: '储水罐',
        volume: 6,
        kind: 'reservoir',
      },
      {
        id: 'D',
        name: '出口泊位',
        volume: 0,
        kind: 'boat',
        exitAt: 4,
      },
      {
        id: 'E',
        name: '储水罐',
        volume: 8,
        kind: 'reservoir',
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'AE',
        a: 'A',
        b: 'E',
        requires: 'A',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'D',
        at: 3,
        powerNeeded: 4,
      },
    ],
    solution: ['BC', 'BC', 'CD', 'CD', 'AB', 'BC', 'AE'],
    requiresIsolation: true,
    design:
      '先分两步从 C 向 B、D 预分配并逐一隔离，压低 C；A—B 触发初轮溢流仍无法下压 A 至 2.5，加入低水 C 后才解锁 A—E。',
  },
  {
    id: 'twin-port-balance',
    title: '双港回平',
    chapter: '04 · 溢流动力站',
    maxMoves: 10,
    par: 8,
    intro: '两条溢流分别通向两个港口。先借高水船舱补另一侧，最后逐个隔离到站。',
    tanks: [
      {
        id: 'A',
        name: '机关舱',
        kind: 'crate',
        volume: 10,
        switchAt: 2,
      },
      {
        id: 'B',
        name: '水轮舱',
        kind: 'wheel',
        volume: 1,
      },
      {
        id: 'C',
        name: '水轮舱',
        kind: 'wheel',
        volume: 1,
      },
      {
        id: 'D',
        name: '出口泊位',
        kind: 'boat',
        volume: 2,
        exitAt: 4,
      },
      {
        id: 'E',
        name: '出口泊位',
        kind: 'boat',
        volume: 0,
        exitAt: 4,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
        requires: 'A',
      },
      {
        id: 'CE',
        a: 'C',
        b: 'E',
      },
    ],
    overflow: [
      {
        from: 'B',
        to: 'D',
        at: 2,
        powerNeeded: 1,
      },
      {
        from: 'C',
        to: 'E',
        at: 2,
        powerNeeded: 1,
      },
    ],
    solution: ['AB', 'AB', 'BC', 'BD', 'CE', 'BC', 'BD', 'CE'],
    requiresIsolation: true,
    design:
      '分支溢流而非串联：B→D 和 C→E。初轮抬高 D 并解锁 B—D；随后借 D 的水把 E 抬高，再用 C—E 平衡。依次隔离 B—C、B—D、C—E，最终让两船都达四格。',
  },
  {
    id: 'path-double-bookends',
    title: '两岸通行证',
    chapter: '04 · 溢流动力站',
    maxMoves: 7,
    par: 6,
    intro: 'D 的开关更低，需要分两次排水。两岸机关都点亮后，隔开右岸，再接入左边高水仓。',
    tanks: [
      {
        id: 'A',
        name: '左岸水仓',
        kind: 'reservoir',
        volume: 8,
      },
      {
        id: 'B',
        name: '左岸机关',
        kind: 'crate',
        volume: 7,
        switchAt: 4.5,
      },
      {
        id: 'C',
        name: '中央港',
        kind: 'boat',
        volume: 0,
        exitAt: 5,
      },
      {
        id: 'D',
        name: '深位机关',
        kind: 'crate',
        volume: 7,
        switchAt: 2,
      },
      {
        id: 'E',
        name: '右岸缓冲',
        kind: 'reservoir',
        volume: 0,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
        requires: ['B', 'D'],
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['DE', 'DE', 'CD', 'BC', 'CD', 'AB'],
    requiresIsolation: true,
    design: '右端机关分两次降水；双锁打开左端补水，中央船舱与右支路隔离。',
  },
  {
    id: 'path-double-middle',
    title: '双锁回灌',
    chapter: '04 · 溢流动力站',
    maxMoves: 8,
    par: 7,
    intro: 'A、C 两盏灯共同控制最后的水仓。先降下两个箱子，再把水补回 D，关好侧阀后升船。',
    tanks: [
      {
        id: 'A',
        name: '首级机关',
        kind: 'crate',
        volume: 9,
        switchAt: 4.5,
      },
      {
        id: 'B',
        name: '过渡水仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'C',
        name: '次级机关',
        kind: 'crate',
        volume: 10,
        switchAt: 3.5,
      },
      {
        id: 'D',
        name: '升船港',
        kind: 'boat',
        volume: 0,
        exitAt: 6.5,
      },
      {
        id: 'E',
        name: '封存水仓',
        kind: 'reservoir',
        volume: 9,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: ['A', 'C'],
      },
    ],
    solution: ['AB', 'BC', 'BC', 'CD', 'BC', 'CD', 'DE'],
    requiresIsolation: true,
    design: '双机关先后锁存；C 经两次分区均衡降低，D 先回灌再隔离升船。',
  },
  {
    id: 'path-central-depot',
    title: '逐站留泊',
    chapter: '05 · 联动总控站',
    maxMoves: 8,
    par: 7,
    intro: '中央仓的水要分两次使用。西港到站后关阀留水，再把余量送往东港，接上最后的高水仓。',
    tanks: [
      {
        id: 'A',
        name: '启航机关',
        kind: 'crate',
        volume: 7,
        switchAt: 4.5,
      },
      {
        id: 'B',
        name: '西侧船坞',
        kind: 'boat',
        volume: 1,
        exitAt: 6,
      },
      {
        id: 'C',
        name: '共享水仓',
        kind: 'reservoir',
        volume: 8,
      },
      {
        id: 'D',
        name: '东侧船坞',
        kind: 'boat',
        volume: 1,
        exitAt: 6.5,
      },
      {
        id: 'E',
        name: '末端水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: ['A'],
      },
    ],
    solution: ['AB', 'AB', 'BC', 'BC', 'CD', 'CD', 'DE'],
    requiresIsolation: true,
    design: '机关开启末端水仓；西船从中央仓升到6并隔离，余水转给东船后再次隔离升到6.75。',
  },
  {
    id: 'star-twin-switches',
    title: '四室落锁',
    chapter: '05 · 联动总控站',
    maxMoves: 8,
    par: 7,
    intro: '两个箱子需要借第四间一起下沉。双灯点亮后，把三条支路逐一关好，集中托起中央小船。',
    tanks: [
      {
        id: 'A',
        name: '左机关',
        kind: 'crate',
        volume: 9,
        switchAt: 4,
      },
      {
        id: 'B',
        name: '中央船坞',
        kind: 'boat',
        volume: 0,
        exitAt: 6.5,
      },
      {
        id: 'C',
        name: '右机关',
        kind: 'crate',
        volume: 5,
        switchAt: 4,
      },
      {
        id: 'D',
        name: '低位缓冲',
        kind: 'reservoir',
        volume: 2,
      },
      {
        id: 'E',
        name: '高位水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'BA',
        a: 'B',
        b: 'A',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'BE',
        a: 'B',
        b: 'E',
        requires: ['A', 'C'],
      },
    ],
    solution: ['BA', 'BC', 'BD', 'BA', 'BC', 'BD', 'BE'],
    requiresIsolation: true,
    design: '四槽同时均衡至4点亮两机关；三个低位分支均需切断才能以高水仓升中央船。',
  },
  {
    id: 'star-core-switch',
    title: '先寄存，再取回',
    chapter: '05 · 联动总控站',
    maxMoves: 8,
    par: 7,
    intro: '先把一部分水寄存在船港，再借空仓压低中央箱子。开关点亮后隔开空仓，把寄存水重新连回来。',
    tanks: [
      {
        id: 'A',
        name: '寄存船港',
        kind: 'boat',
        volume: 3,
        exitAt: 6,
      },
      {
        id: 'B',
        name: '中央机关',
        kind: 'crate',
        volume: 5,
        switchAt: 2,
      },
      {
        id: 'C',
        name: '辅助水仓',
        kind: 'reservoir',
        volume: 8,
      },
      {
        id: 'D',
        name: '排水空仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'E',
        name: '封存水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'BA',
        a: 'B',
        b: 'A',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'BE',
        a: 'B',
        b: 'E',
        requires: ['B'],
      },
    ],
    solution: ['BA', 'BA', 'BD', 'BD', 'BA', 'BC', 'BE'],
    requiresIsolation: true,
    design: '以船舱临时储水降低中央机关；隔离船舱后与空仓排水触发开关，再回收船舱与两水仓抬升。',
  },
  {
    id: 'star-double-core',
    title: '中心双机关',
    chapter: '05 · 联动总控站',
    maxMoves: 8,
    par: 7,
    intro: '先让船港暂存一份水，再借空仓同时降低 A、B。双灯点亮后，回收寄存水和高水仓的水。',
    tanks: [
      {
        id: 'A',
        name: '外侧机关',
        kind: 'crate',
        volume: 6,
        switchAt: 3,
      },
      {
        id: 'B',
        name: '中心机关',
        kind: 'crate',
        volume: 5,
        switchAt: 4,
      },
      {
        id: 'C',
        name: '暂存船港',
        kind: 'boat',
        volume: 2,
        exitAt: 4.5,
      },
      {
        id: 'D',
        name: '低位缓冲',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'E',
        name: '双锁水仓',
        kind: 'reservoir',
        volume: 9,
      },
    ],
    gates: [
      {
        id: 'BA',
        a: 'B',
        b: 'A',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'BE',
        a: 'B',
        b: 'E',
        requires: ['A', 'B'],
      },
    ],
    solution: ['BA', 'BC', 'BC', 'BD', 'BA', 'BC', 'BE'],
    requiresIsolation: true,
    design: '船舱先存水并隔离；中心和支路机关同时降水，隔开支路机关后回收船水、开启双锁高仓。',
  },
  {
    id: 'tee-three-stations',
    title: '借港存水',
    chapter: '05 · 联动总控站',
    maxMoves: 8,
    par: 7,
    intro:
      '先点亮 C，把它留作低水缓冲。借 D 暂存一份水并关好阀，再接回 C 降低 A，解锁船港的补水仓。',
    tanks: [
      {
        id: 'A',
        name: '主机关',
        kind: 'crate',
        volume: 7,
        switchAt: 4,
      },
      {
        id: 'B',
        name: '分流仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'C',
        name: '缓冲机关',
        kind: 'crate',
        volume: 5,
        switchAt: 4,
      },
      {
        id: 'D',
        name: '暂存船港',
        kind: 'boat',
        volume: 3,
        exitAt: 6.5,
      },
      {
        id: 'E',
        name: '双锁水仓',
        kind: 'reservoir',
        volume: 9,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: ['A', 'C'],
      },
    ],
    solution: ['BC', 'BC', 'AB', 'BD', 'BD', 'BC', 'DE'],
    requiresIsolation: true,
    design: 'C 先锁存并隔离；船港用于暂存高水，隔开船港后低位 C 回接压下 A，最终独立升船。',
  },
  {
    id: 'tee-dual-boats',
    title: '优先放行',
    chapter: '05 · 联动总控站',
    maxMoves: 8,
    par: 7,
    intro:
      '先调匀 B、C，把左港送到出口并关阀留水。右边几个房间随后一起降液位，机关与第二艘船同时到位。',
    tanks: [
      {
        id: 'A',
        name: '优先船港',
        kind: 'boat',
        volume: 3,
        exitAt: 6,
      },
      {
        id: 'B',
        name: '高位仓',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'C',
        name: '末级机关',
        kind: 'crate',
        volume: 8,
        switchAt: 4.5,
      },
      {
        id: 'D',
        name: '空缓冲仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'E',
        name: '联动船港',
        kind: 'boat',
        volume: 3,
        exitAt: 4.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['BC', 'BC', 'AB', 'AB', 'BC', 'BD', 'DE'],
    requiresIsolation: true,
    design: '先借高位机关为 B 配水，完成并隔离左船；其余四槽共享水位使机关与右船在4.5同时达标。',
  },
  {
    id: 'star-twin-boats',
    title: '双港分批供水',
    chapter: '05 · 联动总控站',
    maxMoves: 9,
    par: 8,
    intro: '先借两座船港降低 D，解锁高水仓。两个出口高度不同，要分批供水，先留住高港的水。',
    tanks: [
      {
        id: 'A',
        name: '低位船港',
        kind: 'boat',
        volume: 1,
        exitAt: 4.5,
      },
      {
        id: 'B',
        name: '分配水仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'C',
        name: '高位船港',
        kind: 'boat',
        volume: 1,
        exitAt: 5,
      },
      {
        id: 'D',
        name: '枢纽机关',
        kind: 'crate',
        volume: 10,
        switchAt: 3.5,
      },
      {
        id: 'E',
        name: '上游水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'BA',
        a: 'B',
        b: 'A',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'BE',
        a: 'B',
        b: 'E',
        requires: ['D'],
      },
    ],
    solution: ['BA', 'BC', 'BD', 'BA', 'BD', 'BE', 'BC', 'BA'],
    requiresIsolation: true,
    design: '四槽降箱后隔离低目标船与机关；先升高目标船并隔离，再用余水升低目标船。',
  },
  {
    id: 'tee-crate-fork',
    title: '叉口双钥',
    chapter: '05 · 联动总控站',
    maxMoves: 9,
    par: 8,
    intro:
      '先让船港暂存水，再把中心机关与外侧机关分两步降下。两把钥匙齐全后，接回各舱共同迎接补水。',
    tanks: [
      {
        id: 'A',
        name: '空水仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'B',
        name: '中心机关',
        kind: 'crate',
        volume: 5,
        switchAt: 2.5,
      },
      {
        id: 'C',
        name: '寄存船港',
        kind: 'boat',
        volume: 2,
        exitAt: 4.5,
      },
      {
        id: 'D',
        name: '外侧机关',
        kind: 'crate',
        volume: 6,
        switchAt: 3,
      },
      {
        id: 'E',
        name: '双锁水仓',
        kind: 'reservoir',
        volume: 10,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
        requires: ['B', 'D'],
      },
    ],
    solution: ['BC', 'BD', 'BC', 'BD', 'AB', 'BD', 'BC', 'DE'],
    requiresIsolation: true,
    design: '船港先存水并与双机关分离；空仓先降中心、再降外侧，双锁放行后五槽整体升船。',
  },
  {
    id: 'tee-remote-ferries',
    title: '隔舱接力',
    chapter: '05 · 联动总控站',
    maxMoves: 9,
    par: 8,
    intro: '先借低水仓压下远端箱子，解锁左港。左港到站后留住水，再隔开机关舱，把剩余补水送往右港。',
    tanks: [
      {
        id: 'A',
        name: '左船港',
        kind: 'boat',
        volume: 2,
        exitAt: 5,
      },
      {
        id: 'B',
        name: '中转水仓',
        kind: 'reservoir',
        volume: 0,
      },
      {
        id: 'C',
        name: '主水仓',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'D',
        name: '右船港',
        kind: 'boat',
        volume: 2,
        exitAt: 4.5,
      },
      {
        id: 'E',
        name: '远端机关',
        kind: 'crate',
        volume: 9,
        switchAt: 4.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
        requires: ['E'],
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'BD',
        a: 'B',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['BD', 'DE', 'AB', 'BD', 'BC', 'AB', 'DE', 'BD'],
    requiresIsolation: true,
    design: '远端机关解锁左船支路；右部隔离后先升左船，再隔离左船与末端机关，调余水升右船。',
  },
  {
    id: 'path-dual-ferry',
    title: '东西双航线',
    chapter: '05 · 联动总控站',
    maxMoves: 10,
    par: 9,
    intro: '两艘船必须同时到站。先给东港留住一份水，再借西港压下中央机关，最后补足西港液位。',
    tanks: [
      {
        id: 'A',
        name: '西港',
        kind: 'boat',
        volume: 0,
        exitAt: 5,
      },
      {
        id: 'B',
        name: '西岸水仓',
        kind: 'reservoir',
        volume: 10,
      },
      {
        id: 'C',
        name: '中央机关',
        kind: 'crate',
        volume: 6,
        switchAt: 4.5,
      },
      {
        id: 'D',
        name: '东岸水仓',
        kind: 'reservoir',
        volume: 8,
      },
      {
        id: 'E',
        name: '东港',
        kind: 'boat',
        volume: 2,
        exitAt: 5.5,
      },
    ],
    gates: [
      {
        id: 'AB',
        a: 'A',
        b: 'B',
      },
      {
        id: 'BC',
        a: 'B',
        b: 'C',
      },
      {
        id: 'CD',
        a: 'C',
        b: 'D',
      },
      {
        id: 'DE',
        a: 'D',
        b: 'E',
      },
    ],
    solution: ['BC', 'BC', 'CD', 'DE', 'DE', 'BC', 'CD', 'AB', 'CD'],
    requiresIsolation: true,
    design: '先以中央机关转存左侧水量，再封存东港；西侧降箱后重新并入中右水仓完成双船不同高度。',
  },
];

export default LEVELS;
