export const CARDS = [
  {
    "text": "自身发生升级事件后，使其他己方战场角色中 L 最低的一名成长 +1〔link〕；无其他角色则不触发。",
    "health": 7,
    "key": "tuner",
    "attack": 2,
    "limit": "备战·战场；每回合最多 1 次，有合法联动目标才占用次数。",
    "id": "character.resonance.tuner",
    "type": "character",
    "family": "resonance",
    "name": "鸣律学徒",
    "tier": 1
  },
  {
    "text": "其他己方战场角色发生升级事件后，自身成长 +1〔link〕。",
    "health": 11,
    "key": "echo_guard",
    "attack": 2,
    "limit": "备战·战场；每回合前 2 次符合条件的事件。",
    "id": "character.resonance.echo_guard",
    "type": "character",
    "family": "resonance",
    "name": "回声卫士",
    "tier": 2
  },
  {
    "text": "其他己方战场角色发生升级事件后，使除自身及本次升级角色外 L 最低的至多两名己方战场角色各成长 +1〔link〕。",
    "health": 17,
    "key": "conductor",
    "attack": 4,
    "limit": "备战·战场；每回合最多 1 次；至少有一名合法联动目标才占用次数。",
    "id": "character.resonance.conductor",
    "type": "character",
    "family": "resonance",
    "name": "合奏领主",
    "tier": 4
  },
  {
    "text": "选择两名不同己方战场角色，按选择顺序各成长 +1〔gain〕；两个目标分别产生一次升级事件。少于两名合法角色不能施放。",
    "health": 0,
    "key": "chorus",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗。",
    "id": "spell.resonance.chorus",
    "type": "spell",
    "family": "resonance",
    "name": "齐鸣练习",
    "tier": 1
  },
  {
    "text": "选择一名己方战场角色成长 +3〔gain〕；其升级事件及监听结算后，使其他己方战场角色中 L 最低的一名成长 +1〔link〕。允许只有主目标时施放，第二段无目标则结束。",
    "health": 0,
    "key": "breakthrough",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗。",
    "id": "spell.resonance.breakthrough",
    "type": "spell",
    "family": "resonance",
    "name": "节拍跃升",
    "tier": 4
  },
  {
    "text": "固定 +3 最大生命。佩戴者发生升级事件后，使其他己方战场角色中 L 最低的一名成长 +1〔link〕。",
    "health": 0,
    "key": "badge",
    "attack": 0,
    "limit": "备战·佩戴者在战场；每回合最多 1 次，有合法联动目标才占用次数。",
    "id": "equipment.resonance.badge",
    "type": "equipment",
    "family": "resonance",
    "name": "同调徽记",
    "tier": 2
  },
  {
    "text": "备战阶段开始时，自身成长 +1〔gain〕。本回合购买或部署后不补发已错过的回合开始事件。",
    "health": 8,
    "key": "vessel",
    "attack": 1,
    "limit": "备战开始·战场；每回合 1 次。",
    "id": "character.legacy.vessel",
    "type": "character",
    "family": "legacy",
    "name": "薪火幼徒",
    "tier": 1
  },
  {
    "text": "一次等级转移或交换完成后，若自身 L 相比事务开始时净增加至少 1，获得下场战斗 +3 攻击。",
    "health": 10,
    "key": "successor",
    "attack": 5,
    "limit": "备战·战场；每回合前 1 次满足净增加条件的转移事务。",
    "id": "character.legacy.successor",
    "type": "character",
    "family": "legacy",
    "name": "继承剑士",
    "tier": 3
  },
  {
    "text": "等级转移或交换完成后，若至少一方 L 实际改变，使参与事务的两个己方角色各获得下场战斗护盾 6；允许参与者位于手牌或战场。",
    "health": 22,
    "key": "keeper",
    "attack": 4,
    "limit": "自身须在战场；每回合前 1 次发生实际等级变化的己方转移事务。",
    "id": "character.legacy.keeper",
    "type": "character",
    "family": "legacy",
    "name": "传世守望",
    "tier": 5
  },
  {
    "text": "依次选择不同的己方角色 A、B，均可在战场或手牌；要求 A 的 L>1。把 A 的全部 G=L−1 转给 B，A 变 L1，B 增加 G；发一次 LevelTransferred，不产生升级事件。转移完成后给 B 下场战斗护盾 6。",
    "health": 0,
    "key": "bequest",
    "attack": 0,
    "limit": "手牌施放 → 战场/手牌；一次性消耗；A=B 或 A 的 L=1 时不允许确认。",
    "id": "spell.legacy.bequest",
    "type": "spell",
    "family": "legacy",
    "name": "传承之契",
    "tier": 3
  },
  {
    "text": "选择不同且 L 不同的己方角色 A、B，均可在战场或手牌，交换二者 G。只发一次 LevelsSwapped，不发 LevelTransferred 或升级事件；接收判定只看最终净增加，不能把双向交换算成两次接收。",
    "health": 0,
    "key": "exchange",
    "attack": 0,
    "limit": "手牌施放 → 战场/手牌；一次性消耗；A=B 或两者 L 相同时不允许确认。",
    "id": "spell.legacy.exchange",
    "type": "spell",
    "family": "legacy",
    "name": "换位授业",
    "tier": 4
  },
  {
    "text": "固定 +3 最大生命。一次转移事务完成后，若佩戴者 L 净减少至少 1，佩戴者获得下场战斗护盾 6。",
    "health": 0,
    "key": "amulet",
    "attack": 0,
    "limit": "备战·佩戴者在战场；每回合前 1 次满足净减少条件的事务。",
    "id": "equipment.legacy.amulet",
    "type": "equipment",
    "family": "legacy",
    "name": "余火护符",
    "tier": 3
  },
  {
    "text": "完成付费刷新后，自身成长 +1〔gain〕。",
    "health": 6,
    "key": "broker",
    "attack": 2,
    "limit": "备战·战场；每回合前 1 次自身在场时发生的 PaidRerolled。",
    "id": "character.commerce.broker",
    "type": "character",
    "family": "commerce",
    "name": "巡街掮客",
    "tier": 1
  },
  {
    "text": "出售其他己方角色后，额外获得 1 金；被出售者可来自战场或手牌。不能从出售自身、装备、法术、合并材料或战斗阵亡获得奖励。",
    "health": 10,
    "key": "bookkeeper",
    "attack": 2,
    "limit": "备战·战场；每回合前 1 次符合条件的出售；受每名指挥官每回合额外产金 3 金上限限制，上限已满仍占用本卡次数。",
    "id": "character.commerce.bookkeeper",
    "type": "character",
    "family": "commerce",
    "name": "盘账掌柜",
    "tier": 2
  },
  {
    "text": "完成付费刷新后，当前商店最左侧未售角色的成交价 −1，最低 1 金；无角色则无效果。折扣只属于该商品实例。",
    "health": 15,
    "key": "magnate",
    "attack": 5,
    "limit": "备战·战场 → 商店；每回合前 3 次自身在场时发生的 PaidRerolled。",
    "id": "character.commerce.magnate",
    "type": "character",
    "family": "commerce",
    "name": "云市巨贾",
    "tier": 4
  },
  {
    "text": "立即免费重抽商店全部 5 格，再使新商店最左角色成交价 −1，最低 1 金。保留 3角色/1法术/1装备槽结构；不产生 PaidRerolled。",
    "health": 0,
    "key": "open_market",
    "attack": 0,
    "limit": "手牌施放 → 商店；一次性消耗，属于 effect 刷新；原商品及折扣被替换。",
    "id": "spell.commerce.open_market",
    "type": "spell",
    "family": "commerce",
    "name": "开市号角",
    "tier": 1
  },
  {
    "text": "先选择角色、法术或装备一种类型，只重抽商店中该类型的固定槽，包括该类型已购买形成的空槽；其他槽保持原商品、空位及折扣。新卡继续按 P 和品阶概率抽取。",
    "health": 0,
    "key": "targeted_order",
    "attack": 0,
    "limit": "手牌施放 → 商店；一次性消耗，属于 effect 刷新，不产生 PaidRerolled；不改变槽位类型。",
    "id": "spell.commerce.targeted_order",
    "type": "spell",
    "family": "commerce",
    "name": "定向进货",
    "tier": 3
  },
  {
    "text": "固定 +1 攻击、+1 最大生命。完成付费刷新后，佩戴者获得下场战斗 +1 攻击，可累加。",
    "health": 0,
    "key": "abacus",
    "attack": 0,
    "limit": "备战·佩戴者在战场；每回合前 3 次在场时发生的 PaidRerolled。",
    "id": "equipment.commerce.abacus",
    "type": "equipment",
    "family": "commerce",
    "name": "旅行算盘",
    "tier": 1
  },
  {
    "text": "成功施放一张法术后，自身成长 +1〔gain〕。",
    "health": 8,
    "key": "apprentice",
    "attack": 3,
    "limit": "备战·战场；每回合前 1 次自身在场时发生的 SpellCast。",
    "id": "character.arcana.apprentice",
    "type": "character",
    "family": "arcana",
    "name": "烛火学者",
    "tier": 2
  },
  {
    "text": "成功施放法术后，为自身附加一次下场战斗开场射击：对随机敌人造成自身结算该次射击时当前攻击值的伤害。射击按附加顺序逐次执行，每次重新选敌人。",
    "health": 11,
    "key": "cannoneer",
    "attack": 3,
    "limit": "备战·战场监听；每回合前 3 次 SpellCast 各加一次射击。射击只在自身参战且仍存活时执行。",
    "id": "character.arcana.cannoneer",
    "type": "character",
    "family": "arcana",
    "name": "符文炮手",
    "tier": 3
  },
  {
    "text": "成功施放法术后，使此刻所有己方战场角色获得下场战斗 +1 攻击，包括自身。之后新上场的角色不补领。",
    "health": 19,
    "key": "archivist",
    "attack": 4,
    "limit": "备战·战场；每回合前 3 次自身在场时发生的 SpellCast。",
    "id": "character.arcana.archivist",
    "type": "character",
    "family": "arcana",
    "name": "万卷术主",
    "tier": 5
  },
  {
    "text": "选择己方战场角色，为其附加下场战斗开场效果：对随机敌人造成 4+自身当时 L 点伤害。",
    "health": 0,
    "key": "firemark",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗；同名准备效果可多次附加，逐个执行，准备者须仍存活。",
    "id": "spell.arcana.firemark",
    "type": "spell",
    "family": "arcana",
    "name": "焰印",
    "tier": 2
  },
  {
    "text": "选择己方战场角色，为其附加下场战斗开场效果：读取准备者当时当前攻击 A，对全部存活敌人同时各造成 floor(A/2) 点伤害，即向下取整，可以为 0。",
    "health": 0,
    "key": "starfall",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗；同名准备效果可多次附加，逐个执行，准备者须仍存活。",
    "id": "spell.arcana.starfall",
    "type": "spell",
    "family": "arcana",
    "name": "星落仪式",
    "tier": 5
  },
  {
    "text": "固定 +1 攻击、+3 最大生命。成功施放法术后，佩戴者获得下场战斗 +2 攻击，可累加。",
    "health": 0,
    "key": "grimoire",
    "attack": 0,
    "limit": "备战·佩戴者在战场；每回合前 2 次在场时发生的 SpellCast。",
    "id": "equipment.arcana.grimoire",
    "type": "equipment",
    "family": "arcana",
    "name": "充能法典",
    "tier": 3
  },
  {
    "text": "战斗开始时，若自身至少装备 1 件装备，获得护盾 4。",
    "health": 8,
    "key": "rivet_guard",
    "attack": 1,
    "limit": "战斗·战场；每场 1 次，只检查开场装备快照。",
    "id": "character.armory.rivet_guard",
    "type": "character",
    "family": "armory",
    "name": "铆钉卫士",
    "tier": 1
  },
  {
    "text": "备战阶段开始时，若自身已装备 2 件装备，成长 +1〔gain〕。回合开始之后换装不补触发。",
    "health": 12,
    "key": "forge_walker",
    "attack": 3,
    "limit": "备战开始·战场；每回合 1 次。",
    "id": "character.armory.forge_walker",
    "type": "character",
    "family": "armory",
    "name": "锻炉行者",
    "tier": 3
  },
  {
    "text": "战斗开始时，使所有已装备 2 件装备的己方角色各获得护盾 6，可包含自身。",
    "health": 20,
    "key": "commander",
    "attack": 5,
    "limit": "战斗·战场；每场 1 次，只检查开场装备快照。",
    "id": "character.armory.commander",
    "type": "character",
    "family": "armory",
    "name": "万械统领",
    "tier": 5
  },
  {
    "text": "选择己方战场角色；施法时已装备至少 1 件，则附加下场战斗护盾 8，否则附加护盾 4。护盾数在施法时确定，之后换装不重算。",
    "health": 0,
    "key": "reinforce",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗，可重复使用并叠加护盾。",
    "id": "spell.armory.reinforce",
    "type": "spell",
    "family": "armory",
    "name": "临战加固",
    "tier": 2
  },
  {
    "text": "选择已装备至少 1 件装备的己方战场角色，按施法时装备件数，每件给予下场战斗 +4 攻击。之后换装不重算，0 件装备时不能选择。",
    "health": 0,
    "key": "overload",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗，可重复使用；每张最多提供 +8 临战攻击。",
    "id": "spell.armory.overload",
    "type": "spell",
    "family": "armory",
    "name": "战械超载",
    "tier": 4
  },
  {
    "text": "固定 +6 最大生命。战斗开始时，佩戴者获得 L+2 点护盾；L 取该次开场结算时角色永久等级。",
    "health": 0,
    "key": "tempered_plate",
    "attack": 0,
    "limit": "战斗·佩戴者在战场；每场 1 次。附加最大生命不随 L 变化。",
    "id": "equipment.armory.tempered_plate",
    "type": "equipment",
    "family": "armory",
    "name": "百炼战甲",
    "tier": 4
  },
  {
    "text": "自身阵亡后，在原格召唤一个 2 攻/3 血、无技能的灰烬纸偶；原格已被占用则取己方最左空格，无空格或召唤次数已满则失败。",
    "health": 8,
    "key": "gravekeeper",
    "attack": 1,
    "limit": "战斗·自身阵亡快照；每场自身前 1 次阵亡。临时纸偶没有本技能。",
    "id": "character.ember.gravekeeper",
    "type": "character",
    "family": "ember",
    "name": "纸偶守墓人",
    "tier": 1
  },
  {
    "text": "其他己方角色阵亡后，包括临时召唤物，自身获得本场战斗 +1 攻击并恢复 2 生命。",
    "health": 12,
    "key": "reaper",
    "attack": 3,
    "limit": "战斗·自身须存活在战场；每场前 6 次符合条件的阵亡。与自身同时阵亡不触发。",
    "id": "character.ember.reaper",
    "type": "character",
    "family": "ember",
    "name": "余烬收割者",
    "tier": 3
  },
  {
    "text": "其他己方角色阵亡后，包括临时召唤物，对当前生命值最低的存活敌人造成自身当前攻击值伤害；平局按敌方站位顺序选最左。",
    "health": 17,
    "key": "queen",
    "attack": 4,
    "limit": "战斗·自身须存活在战场；每场前 3 次符合条件的阵亡。与自身同时阵亡不触发。",
    "id": "character.ember.queen",
    "type": "character",
    "family": "ember",
    "name": "焚冕女王",
    "tier": 4
  },
  {
    "text": "选择己方战场角色，要求此时至少有两名己方战场角色。附加下场战斗开场效果：先使此刻其他存活己方角色各获得本场 +2 攻击，再使准备者生命归零并按阵亡结算。主动阵亡不被免死装备阻止。",
    "health": 0,
    "key": "offering",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗；每个角色每回合至多接受一次同名准备。准备者执行时须仍存活。",
    "id": "spell.ember.offering",
    "type": "spell",
    "family": "ember",
    "name": "赴火誓约",
    "tier": 1
  },
  {
    "text": "选择己方战场角色，附加下场战斗效果：该角色首次阵亡后，依次尝试召唤两个 1 攻/2 血、无技能的替身纸偶；每次优先原格，其次最左空格。超出占位或召唤次数限制的纸偶不生成，也不延迟补发。",
    "health": 0,
    "key": "paper_reinforcements",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗；每个角色每回合至多接受一次同名准备，每场只响应该角色首次阵亡。",
    "id": "spell.ember.paper_reinforcements",
    "type": "spell",
    "family": "ember",
    "name": "纸偶增援",
    "tier": 3
  },
  {
    "text": "固定 +1 攻击、+2 最大生命。佩戴者阵亡后，使其他存活己方角色各获得护盾 3，包括临时召唤物。",
    "health": 0,
    "key": "wick",
    "attack": 0,
    "limit": "战斗·佩戴者阵亡快照；每场前 1 次佩戴者阵亡。",
    "id": "equipment.ember.wick",
    "type": "equipment",
    "family": "ember",
    "name": "余烬灯芯",
    "tier": 2
  },
  {
    "text": "嘲讽：敌方普通攻击优先选择有嘲讽的角色；多个嘲讽按通用站位顺序选择。本技能不影响指定目标的法术或技能。",
    "health": 8,
    "key": "mercenary",
    "attack": 1,
    "limit": "战斗·战场；存活时持续生效。",
    "id": "character.neutral.mercenary",
    "type": "character",
    "family": "neutral",
    "name": "铁壁佣兵",
    "tier": 1
  },
  {
    "text": "自身主动普攻、同时反击及其全部死亡链结束后，若自身仍存活，为当前生命比例最低的一名存活己方角色恢复 2 生命，可包含自身；平局按站位顺序。",
    "health": 10,
    "key": "medic",
    "attack": 2,
    "limit": "战斗·战场；每次自身 AttackResolved 一次，反击不触发，己方全满血时无实际恢复。",
    "id": "character.neutral.medic",
    "type": "character",
    "family": "neutral",
    "name": "巡游医师",
    "tier": 2
  },
  {
    "text": "自身主动普攻计算伤害时，若目标当前护盾>0，该次主动普攻伤害 +4；正常先扣盾后扣血。",
    "health": 13,
    "key": "shieldbreaker",
    "attack": 5,
    "limit": "战斗·战场；每次主动普攻检查一次；不提高自身当前攻击，不加强反击或技能。",
    "id": "character.neutral.shieldbreaker",
    "type": "character",
    "family": "neutral",
    "name": "破盾猎手",
    "tier": 4
  },
  {
    "text": "自身因伤害损失生命并结算后，若仍存活且当前生命≤最大生命的一半，恢复等于自身当前攻击的生命。",
    "health": 16,
    "key": "duelist",
    "attack": 7,
    "limit": "战斗·战场；每场首次满足条件时 1 次。致死伤害后不能靠本技能复活。",
    "id": "character.neutral.duelist",
    "type": "character",
    "family": "neutral",
    "name": "独行斗士",
    "tier": 5
  },
  {
    "text": "选择一名己方战场或手牌角色，使其成长 +2〔gain〕，只产生一次升级事件。",
    "health": 0,
    "key": "training",
    "attack": 0,
    "limit": "手牌施放 → 战场/手牌；一次性消耗。手牌成长不会让战场限定监听器旁听。",
    "id": "spell.neutral.training",
    "type": "spell",
    "family": "neutral",
    "name": "基础操练",
    "tier": 1
  },
  {
    "text": "依次选择不同的己方角色 A、B，均可在战场或手牌；要求 A 的 L>1。把 A 的全部 G=L−1 转给 B，A 变 L1，B 增加 G；只发一次 LevelTransferred，不发升级事件，也不附赠临战增益。",
    "health": 0,
    "key": "succession",
    "attack": 0,
    "limit": "手牌施放 → 战场/手牌；一次性消耗；A=B 或 A 的 L=1 时不允许确认。",
    "id": "spell.neutral.succession",
    "type": "spell",
    "family": "neutral",
    "name": "薪火交接",
    "tier": 2
  },
  {
    "text": "使此刻所有己方战场角色获得下场战斗 +2 攻击；要求至少一名己方战场角色。之后新上场的角色不补领。",
    "health": 0,
    "key": "rally",
    "attack": 0,
    "limit": "手牌施放 → 战场；一次性消耗，可重复使用并叠加攻击。",
    "id": "spell.neutral.rally",
    "type": "spell",
    "family": "neutral",
    "name": "整备号令",
    "tier": 3
  },
  {
    "text": "选择一名己方战场或手牌角色，使其成长 +4〔gain〕，只产生一次升级事件。",
    "health": 0,
    "key": "potential",
    "attack": 0,
    "limit": "手牌施放 → 战场/手牌；一次性消耗。",
    "id": "spell.neutral.potential",
    "type": "spell",
    "family": "neutral",
    "name": "资质点拨",
    "tier": 5
  },
  {
    "text": "固定 +2 攻击，无其他效果。",
    "health": 0,
    "key": "shortsword",
    "attack": 0,
    "limit": "装备在战场角色身上持续生效；不随 L 缩放。",
    "id": "equipment.neutral.shortsword",
    "type": "equipment",
    "family": "neutral",
    "name": "制式短剑",
    "tier": 1
  },
  {
    "text": "固定 +5 最大生命，无其他效果。",
    "health": 0,
    "key": "coat",
    "attack": 0,
    "limit": "装备在战场角色身上持续生效；不随 L 缩放。",
    "id": "equipment.neutral.coat",
    "type": "equipment",
    "family": "neutral",
    "name": "厚布护衣",
    "tier": 2
  },
  {
    "text": "固定 +4 攻击，无其他效果。",
    "health": 0,
    "key": "spear",
    "attack": 0,
    "limit": "装备在战场角色身上持续生效；不随 L 缩放。",
    "id": "equipment.neutral.spear",
    "type": "equipment",
    "family": "neutral",
    "name": "破阵长枪",
    "tier": 4
  },
  {
    "text": "固定 +5 最大生命。首次伤害将使佩戴者生命≤0时，将该次伤害结算后的生命改为 1。只干预这一次伤害，之后仍可正常阵亡；主动阵亡不受保护。",
    "health": 0,
    "key": "last_stand",
    "attack": 0,
    "limit": "战斗·佩戴者在战场；每场 1 次，扣盾后判断是否致死。",
    "id": "equipment.neutral.last_stand",
    "type": "equipment",
    "family": "neutral",
    "name": "不屈挂坠",
    "tier": 5
  }
];
export const CARD_BY_ID = Object.fromEntries(CARDS.map(card => [card.id, card]));
export const PRICES = { character: 3, spell: 2, equipment: 3 };
export const UPGRADE_COSTS = [0, 5, 8, 11, 14];
export const SHOP_WEIGHTS = [[100,0,0,0,0],[65,35,0,0,0],[40,35,25,0,0],[25,30,30,15,0],[20,25,25,20,10]];
export const FAMILIES = {
  resonance: { name: '共鸣', title: '共鸣成长', color: '#6bc7b0', symbol: '◇', motto: '一人成长，众人回响' },
  legacy: { name: '薪火', title: '传承换核', color: '#edb77a', symbol: '♧', motto: '薪火不灭，强者继承' },
  commerce: { name: '云市', title: '商贸刷新', color: '#efcb70', symbol: '◈', motto: '每一次交易，都是机会' },
  arcana: { name: '秘典', title: '咒术连施', color: '#91a3e5', symbol: '✧', motto: '咒文连缀，星火成河' },
  armory: { name: '锻炉', title: '军械锻造', color: '#79b4c5', symbol: '⚒', motto: '百炼成钢，以器立身' },
  ember: { name: '余烬', title: '余烬牺牲', color: '#e99378', symbol: '♜', motto: '落幕之处，亦是新生' },
  neutral: { name: '旅人', title: '中立旅人', color: '#b3b6a4', symbol: '✦', motto: '万般道路，皆可同行' }
};
const bonuses = { badge:[0,3], amulet:[0,3], abacus:[1,1], grimoire:[1,3], tempered_plate:[0,6], wick:[1,2], shortsword:[2,0], coat:[0,5], spear:[4,0], last_stand:[0,5] };
for (const card of CARDS) if (bonuses[card.key]) [card.attackBonus,card.healthBonus] = bonuses[card.key];